import type { Listing } from './types'

export const SEED_LISTINGS: Listing[] = [
  {
    id: '1',
    listing_reference: 'LS-2026-0001',
    title: 'Luxury 2-Bed Apartment',
    property_name: 'Luxury 2-Bed Apartment',
    property_location: 'Shoreditch, London E2',
    property_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=80',
    listing_type: 'short_stay',
    space_type: 'entire_home',
    status: 'live',
    published: true,
    channels: [
      { name: 'airbnb' },
      { name: 'booking_com' },
      { name: 'direct' },
      { name: 'vrbo' },
      { name: 'rightmove' },
    ],
    availability_status: 'Open',
    availability_note: 'Next blocked 24 Jun – 25 Jun',
    price_display: 'From £180 per night',
    occupancy_mtd: 68,
    adr_mtd: 19600,
    adr_display: '£196 ADR',
    direct_page_status: 'live',
    quality_score: 92,
  },
  {
    id: '2',
    listing_reference: 'LS-2026-0002',
    title: 'Bright Double Room',
    property_name: 'Bright Double Room',
    property_location: 'Salford, M5',
    property_image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=80',
    listing_type: 'short_stay',
    space_type: 'private_room',
    status: 'live',
    published: true,
    channels: [
      { name: 'airbnb' },
      { name: 'booking_com' },
    ],
    availability_status: 'Open',
    availability_note: 'No blocks',
    price_display: 'From £60 per night',
    occupancy_mtd: 52,
    adr_mtd: 6200,
    adr_display: '£62 ADR',
    direct_page_status: 'live',
    quality_score: 85,
  },
  {
    id: '3',
    listing_reference: 'LS-2026-0003',
    title: '3-Bed House with Garden',
    property_name: '3-Bed House with Garden',
    property_location: 'Chorlton, M21',
    property_image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=80',
    listing_type: 'short_stay',
    space_type: 'entire_home',
    status: 'live',
    published: true,
    channels: [
      { name: 'airbnb' },
      { name: 'booking_com' },
      { name: 'direct' },
      { name: 'rightmove' },
    ],
    availability_status: '2 days blocked',
    availability_note: '17 Jun – 18 Jun / 29 Jun – 30 Jun',
    price_display: 'From £230 per night',
    occupancy_mtd: 71,
    adr_mtd: 24800,
    adr_display: '£248 ADR',
    direct_page_status: 'live',
    quality_score: 89,
  },
  {
    id: '4',
    listing_reference: 'LS-2026-0004',
    title: 'Modern 2-Bed Apartment',
    property_name: 'Modern 2-Bed Apartment',
    property_location: 'Spinningfields, M3',
    property_image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=80',
    listing_type: 'long_term',
    space_type: 'entire_home',
    status: 'live',
    published: true,
    channels: [
      { name: 'direct' },
      { name: 'rightmove' },
    ],
    availability_status: 'Available',
    availability_note: 'Min stay 3 months',
    price_display: '£1,750 per month',
    direct_page_status: 'live',
    quality_score: 88,
  },
  {
    id: '5',
    listing_reference: 'LS-2026-0005',
    title: 'Serviced Apartment',
    property_name: 'Serviced Apartment',
    property_location: 'Ancoats, M4',
    property_image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=80',
    listing_type: 'long_term',
    space_type: 'entire_home',
    status: 'live',
    published: true,
    channels: [
      { name: 'direct' },
    ],
    availability_status: 'Available',
    availability_note: 'Min stay 1 month',
    price_display: '£1,950 per month',
    direct_page_status: 'live',
    quality_score: 83,
  },
  {
    id: '6',
    listing_reference: 'LS-2026-0006',
    title: 'Elegant Period Property',
    property_name: 'Elegant Period Property',
    property_location: 'Didsbury, M20',
    property_image: 'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=80',
    listing_type: 'short_stay',
    space_type: 'entire_home',
    status: 'needs_attention',
    published: false,
    channels: [
      { name: 'airbnb' },
      { name: 'booking_com' },
      { name: 'rightmove' },
    ],
    availability_status: '3 days blocked',
    availability_note: '20 Jun – 21 Jun / 26 Jun – 27 Jun',
    price_display: 'From £210 per night',
    occupancy_mtd: 43,
    adr_mtd: 18200,
    adr_display: '£182 ADR',
    direct_page_status: 'draft',
    quality_score: 67,
  },
  {
    id: '7',
    listing_reference: 'LS-2026-0007',
    title: 'Modern Studio Apartment',
    property_name: 'Modern Studio Apartment',
    property_location: 'Northern Quarter, M4',
    property_image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=80',
    listing_type: 'short_stay',
    space_type: 'entire_home',
    status: 'draft',
    published: false,
    channels: [
      { name: 'airbnb' },
      { name: 'booking_com' },
    ],
    availability_status: 'Open',
    availability_note: 'No blocks',
    price_display: 'From £95 per night',
    direct_page_status: 'not_created',
    quality_score: 54,
  },
  {
    id: '8',
    listing_reference: 'LS-2026-0008',
    title: 'Family Home – Long Stay',
    property_name: 'Family Home – Long Stay',
    property_location: 'Altrincham, WA14',
    property_image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=80',
    listing_type: 'long_term',
    space_type: 'entire_home',
    status: 'live',
    published: true,
    channels: [
      { name: 'direct' },
    ],
    availability_status: 'Available',
    availability_note: 'Min stay 6 months',
    price_display: '£2,400 per month',
    direct_page_status: 'live',
    quality_score: 91,
  },
]
