export type ProfileGroup =
  | "residential_rental"
  | "short_stay"
  | "lease_managed"
  | "commercial_mixed"
  | "capital_strategy"

export interface PlanningProfile {
  key: string
  label: string
  icon: string
  description: string
  colour: string
  yieldRange: string
  group: ProfileGroup
  groupLabel: string
  upfrontCostCategories: string[]
  expenseCategories: string[]
  billCategories: string[]
  complianceRequirements: string[]
  typicalUpfront: string
  riskLevel: "Low" | "Medium" | "High"
  managementIntensity: "Low" | "Medium" | "High"
  complianceComplexity: "Low" | "Medium" | "High"
  incomeModel: string
  bestFitPropertyTypes: string[]
  useCase: string
  keyMetrics: string[]
}

export const PLANNING_PROFILES: PlanningProfile[] = [
  // ── Residential Rental ─────────────────────────────────────────────
  {
    key: "long_term_let",
    label: "Long-Term Let",
    icon: "Home",
    description: "Purchase or manage a residential property and let to a single household on an assured shorthold tenancy.",
    colour: "#10B981",
    yieldRange: "4–7% gross yield",
    group: "residential_rental",
    groupLabel: "Residential Rental",
    upfrontCostCategories: ["Purchase deposit", "Stamp duty", "Legal fees", "Survey", "Refurbishment"],
    expenseCategories: ["Mortgage", "Management fee", "Maintenance buffer", "Insurance", "Void allowance"],
    billCategories: [],
    complianceRequirements: ["EPC (min E)", "Gas Safety Certificate", "EICR", "Smoke & CO alarms"],
    typicalUpfront: "£30,000–£100,000+",
    riskLevel: "Low",
    managementIntensity: "Low",
    complianceComplexity: "Low",
    incomeModel: "Monthly AST rent",
    bestFitPropertyTypes: ["Houses", "Flats", "Bungalows"],
    useCase: "Long-term capital growth and steady rental income. Lower management burden.",
    keyMetrics: ["Gross yield", "Net yield", "Void allowance", "Monthly cashflow"],
  },
  {
    key: "hmo",
    label: "HMO",
    icon: "Building2",
    description: "House in Multiple Occupation — let individual rooms to separate tenants for maximum cashflow.",
    colour: "#7C3AED",
    yieldRange: "8–15% gross yield",
    group: "residential_rental",
    groupLabel: "Residential Rental",
    upfrontCostCategories: ["Purchase/deposit", "Refurbishment", "HMO licence", "Compliance", "Furnishing"],
    expenseCategories: ["Mortgage", "Management", "Maintenance buffer", "Cleaning", "Voids", "Insurance"],
    billCategories: ["Gas & Electric", "Water", "Council Tax", "Broadband", "TV licence"],
    complianceRequirements: ["HMO Licence", "Fire Safety", "EPC", "EICR", "Gas Safety Certificate", "Planning (C4/Sui Generis)"],
    typicalUpfront: "£25,000–£80,000",
    riskLevel: "Medium",
    managementIntensity: "High",
    complianceComplexity: "High",
    incomeModel: "Per-room monthly rent",
    bestFitPropertyTypes: ["Large houses", "Former student properties", "Ex-care homes"],
    useCase: "High cashflow strategy. Requires active management and compliance investment.",
    keyMetrics: ["Per-room rent", "Occupancy rate", "Room margin", "HMO yield"],
  },
  {
    key: "student_let",
    label: "Student Let",
    icon: "GraduationCap",
    description: "Let rooms or a whole property to students, typically on academic-year tenancies with seasonal voids.",
    colour: "#2563EB",
    yieldRange: "6–12% gross yield",
    group: "residential_rental",
    groupLabel: "Residential Rental",
    upfrontCostCategories: ["Purchase/deposit", "Furnishing", "Legal", "Compliance"],
    expenseCategories: ["Mortgage", "Management", "Maintenance buffer", "Summer void", "Insurance"],
    billCategories: ["Gas & Electric", "Water", "Broadband", "TV licence"],
    complianceRequirements: ["EPC", "Gas Safety", "EICR", "Fire Safety", "HMO Licence (if applicable)"],
    typicalUpfront: "£20,000–£70,000",
    riskLevel: "Low",
    managementIntensity: "Medium",
    complianceComplexity: "Medium",
    incomeModel: "Academic-year room rents + bills package",
    bestFitPropertyTypes: ["Terraced houses", "Converted student blocks", "Purpose-built student flats"],
    useCase: "Predictable academic year cycle. Strong demand in university towns. Seasonal cashflow.",
    keyMetrics: ["Academic-year gross income", "Summer void cost", "Per-room yield", "Guarantor count"],
  },
  {
    key: "co_living",
    label: "Co-Living",
    icon: "Users",
    description: "Managed shared living spaces with community amenities, operated as a membership or tenancy model.",
    colour: "#0891B2",
    yieldRange: "8–14% gross yield",
    group: "residential_rental",
    groupLabel: "Residential Rental",
    upfrontCostCategories: ["Purchase/deposit", "Premium fit-out", "Amenity fit-out", "Compliance", "Branding"],
    expenseCategories: ["Mortgage", "Community management", "Amenity costs", "Cleaning", "Insurance", "Voids"],
    billCategories: ["Gas & Electric", "Water", "Broadband (high speed)", "TV licence"],
    complianceRequirements: ["HMO Licence (if applicable)", "Fire Safety", "EPC", "EICR", "Gas Safety"],
    typicalUpfront: "£30,000–£120,000",
    riskLevel: "Medium",
    managementIntensity: "High",
    complianceComplexity: "Medium",
    incomeModel: "Per-member monthly all-inclusive fee",
    bestFitPropertyTypes: ["Large houses", "Converted commercial", "Purpose-built blocks"],
    useCase: "Premium shared living targeting young professionals. Community-driven model with amenity income.",
    keyMetrics: ["Per-member revenue", "Occupancy", "Churn rate", "Amenity contribution"],
  },

  // ── Short-Stay & Flexible ──────────────────────────────────────────
  {
    key: "serviced_accommodation",
    label: "Serviced Accommodation",
    icon: "Hotel",
    description: "Short-term lets via Airbnb/Booking.com for nightly or weekly corporate and leisure stays.",
    colour: "#F59E0B",
    yieldRange: "12–30% gross yield",
    group: "short_stay",
    groupLabel: "Short-Stay & Flexible",
    upfrontCostCategories: ["Deposit/purchase", "Premium furnishing", "Platform setup", "Photography", "Compliance"],
    expenseCategories: ["Mortgage/Rent", "Platform fees (15–20%)", "Cleaning per stay", "Consumables", "Management", "Maintenance"],
    billCategories: ["Gas & Electric", "Water", "Council Tax", "Broadband", "TV licence", "Streaming"],
    complianceRequirements: ["Planning permission (C1/C6)", "Fire Risk Assessment", "Gas Safety", "EICR", "Public Liability Insurance"],
    typicalUpfront: "£10,000–£50,000",
    riskLevel: "High",
    managementIntensity: "High",
    complianceComplexity: "High",
    incomeModel: "Nightly ADR × occupancy rate",
    bestFitPropertyTypes: ["City centre flats", "City apartments", "Near hospitals/universities"],
    useCase: "High income in corporate/tourist locations. Occupancy-sensitive. Strong management systems required.",
    keyMetrics: ["ADR", "Occupancy %", "RevPAR", "Net operating income"],
  },
  {
    key: "holiday_let",
    label: "Holiday Let",
    icon: "Sun",
    description: "Furnished Holiday Lettings qualifying properties in tourist and leisure areas.",
    colour: "#0EA5E9",
    yieldRange: "6–14% gross yield",
    group: "short_stay",
    groupLabel: "Short-Stay & Flexible",
    upfrontCostCategories: ["Purchase deposit", "Stamp duty", "Premium furnishing", "Legal", "Setup"],
    expenseCategories: ["Mortgage", "Letting agency fees", "Cleaning", "Maintenance", "Insurance", "Rates"],
    billCategories: ["Gas & Electric", "Water", "Business rates", "Broadband"],
    complianceRequirements: ["FHL criteria: 210 available, 105 let days", "Gas Safety", "EICR", "Fire Safety"],
    typicalUpfront: "£40,000–£150,000+",
    riskLevel: "Medium",
    managementIntensity: "Medium",
    complianceComplexity: "Medium",
    incomeModel: "Seasonal nightly/weekly rates",
    bestFitPropertyTypes: ["Coastal cottages", "Rural retreats", "Lake District/Peak District"],
    useCase: "Tax-advantaged FHL ownership in high-demand holiday locations. Seasonal income profile.",
    keyMetrics: ["Peak season rate", "Annual occupancy", "Net yield", "Seasonal cashflow"],
  },

  // ── Lease / Managed Models ─────────────────────────────────────────
  {
    key: "rent_to_rent",
    label: "Rent-to-Rent",
    icon: "ArrowLeftRight",
    description: "Lease a property from a landlord and sublease rooms at a profit — without owning the asset.",
    colour: "#2563EB",
    yieldRange: "15–35% ROI",
    group: "lease_managed",
    groupLabel: "Lease & Managed Models",
    upfrontCostCategories: ["Landlord deposit", "Rent in advance", "Furnishing", "Setup costs", "Compliance outlay"],
    expenseCategories: ["Landlord guaranteed rent", "Management", "Maintenance buffer", "Cleaning", "Voids"],
    billCategories: ["Gas & Electric", "Water", "Council Tax", "Broadband", "TV licence"],
    complianceRequirements: ["EPC (min E)", "Gas Safety Certificate", "EICR", "Fire Risk Assessment", "HMO Licence (if applicable)"],
    typicalUpfront: "£3,000–£12,000",
    riskLevel: "Medium",
    managementIntensity: "High",
    complianceComplexity: "Medium",
    incomeModel: "Room rents minus landlord rent and bills",
    bestFitPropertyTypes: ["HMOs", "Large houses", "Blocks of rooms"],
    useCase: "Asset-light. Control property without purchasing. Suited to operators with strong management systems.",
    keyMetrics: ["Operator margin", "Breakeven month", "Landlord rent vs room income", "Cash buffer"],
  },
  {
    key: "social_housing",
    label: "Social Housing",
    icon: "Heart",
    description: "Let to councils, housing associations or exempt accommodation providers under guaranteed lease.",
    colour: "#DC2626",
    yieldRange: "4–6% (guaranteed)",
    group: "lease_managed",
    groupLabel: "Lease & Managed Models",
    upfrontCostCategories: ["Purchase deposit", "Stamp duty", "Legal", "Compliance upgrades", "Refurbishment to standard"],
    expenseCategories: ["Mortgage", "Insurance", "Maintenance buffer"],
    billCategories: [],
    complianceRequirements: ["EPC min D", "Gas Safety", "EICR", "Fire Safety", "Decent Homes Standard"],
    typicalUpfront: "£20,000–£80,000",
    riskLevel: "Low",
    managementIntensity: "Low",
    complianceComplexity: "Medium",
    incomeModel: "Guaranteed monthly rent from authority/HA",
    bestFitPropertyTypes: ["Houses", "Flats", "Converted properties"],
    useCase: "Guaranteed income, lower management burden, strong social impact. Below-market yield.",
    keyMetrics: ["Guaranteed rent", "Contract term", "Repair obligation cost", "Net cashflow"],
  },
  {
    key: "build_to_rent",
    label: "Build-to-Rent",
    icon: "Construction",
    description: "Purpose-built or converted residential blocks operated as a single managed rental asset.",
    colour: "#1E40AF",
    yieldRange: "4–7% stabilised yield",
    group: "lease_managed",
    groupLabel: "Lease & Managed Models",
    upfrontCostCategories: ["Land/purchase", "Construction/conversion", "Planning", "Finance costs", "Amenity fit-out"],
    expenseCategories: ["Finance costs", "Management platform", "Maintenance", "Amenity costs", "Insurance"],
    billCategories: ["Utilities (common areas)", "Broadband infrastructure"],
    complianceRequirements: ["Planning permission", "Building regulations", "Fire Safety Act", "EWS1", "Gas/EICR per unit"],
    typicalUpfront: "£200,000–£5m+",
    riskLevel: "Medium",
    managementIntensity: "High",
    complianceComplexity: "High",
    incomeModel: "Stabilised rent roll across multiple units",
    bestFitPropertyTypes: ["Apartment blocks", "Converted offices/commercial", "Purpose-built schemes"],
    useCase: "Institutional-grade rental product. Longer development horizon. Strong long-term cashflow at scale.",
    keyMetrics: ["Unit count", "Stabilised occupancy", "Net operating income", "DSCR"],
  },

  // ── Commercial & Mixed ─────────────────────────────────────────────
  {
    key: "commercial",
    label: "Commercial",
    icon: "Building",
    description: "Office, retail, or industrial properties let to business tenants on commercial leases.",
    colour: "#64748B",
    yieldRange: "5–10% gross yield",
    group: "commercial_mixed",
    groupLabel: "Commercial & Mixed",
    upfrontCostCategories: ["Purchase deposit", "Stamp duty (SDLT)", "Legal/survey", "Refurbishment"],
    expenseCategories: ["Mortgage", "Management", "Maintenance buffer", "Insurance", "Service charge"],
    billCategories: [],
    complianceRequirements: ["EPC", "Fire Risk Assessment", "Asbestos survey", "Legionella assessment"],
    typicalUpfront: "£50,000–£500,000+",
    riskLevel: "Medium",
    managementIntensity: "Low",
    complianceComplexity: "Medium",
    incomeModel: "Commercial lease rent",
    bestFitPropertyTypes: ["Offices", "Retail units", "Industrial", "Warehouses"],
    useCase: "Longer leases, FRI tenants, lower management burden. Suitable for experienced investors.",
    keyMetrics: ["Lease length", "Break clause date", "Rent review schedule", "Tenant covenant"],
  },
  {
    key: "mixed_use",
    label: "Mixed Use",
    icon: "LayoutGrid",
    description: "Properties combining residential and commercial elements — e.g. flat above a shop.",
    colour: "#8B5CF6",
    yieldRange: "6–12% gross yield",
    group: "commercial_mixed",
    groupLabel: "Commercial & Mixed",
    upfrontCostCategories: ["Purchase deposit", "Stamp duty", "Legal", "Refurbishment", "Planning"],
    expenseCategories: ["Mortgage", "Management", "Maintenance", "Insurance"],
    billCategories: [],
    complianceRequirements: ["EPC (all units)", "Fire Risk Assessment", "Planning compliance", "Gas/EICR per unit"],
    typicalUpfront: "£40,000–£200,000",
    riskLevel: "Medium",
    managementIntensity: "Medium",
    complianceComplexity: "Medium",
    incomeModel: "Blended residential + commercial income",
    bestFitPropertyTypes: ["High street shops with flats", "Mixed-use conversions"],
    useCase: "Diversified income from same asset. Good value-add potential. Complex financing.",
    keyMetrics: ["Blended yield", "Residential income", "Commercial income", "Occupancy split"],
  },

  // ── Capital Strategy ───────────────────────────────────────────────
  {
    key: "refinancing",
    label: "Refinancing",
    icon: "RefreshCw",
    description: "Refinance an existing property to release equity, reduce monthly payments or change lender terms.",
    colour: "#059669",
    yieldRange: "Cash-out + yield improvement",
    group: "capital_strategy",
    groupLabel: "Capital Strategy",
    upfrontCostCategories: ["Valuation fee", "Legal fees", "Arrangement fees", "ERC (if applicable)"],
    expenseCategories: ["New mortgage payment", "Management", "Insurance"],
    billCategories: [],
    complianceRequirements: ["EPC (lender requirement)", "Gas Safety", "EICR"],
    typicalUpfront: "£1,500–£5,000",
    riskLevel: "Low",
    managementIntensity: "Low",
    complianceComplexity: "Low",
    incomeModel: "Reduced monthly cost / equity release",
    bestFitPropertyTypes: ["All owned property types"],
    useCase: "Capital recycling. Improve cashflow. Extract equity for further investment. Requires uplift in value.",
    keyMetrics: ["Current LTV", "Target LTV", "Cash-out potential", "Monthly saving", "DSCR"],
  },
  {
    key: "dev_flip",
    label: "Dev / Flip",
    icon: "Hammer",
    description: "Buy below market value, refurbish or develop, then sell or refinance for profit.",
    colour: "#F97316",
    yieldRange: "15–40% profit on cost",
    group: "capital_strategy",
    groupLabel: "Capital Strategy",
    upfrontCostCategories: ["Purchase price", "Stamp duty", "Legal", "Renovation budget", "Finance costs", "Contingency"],
    expenseCategories: ["Bridging finance", "Project management", "Materials", "Labour", "Insurance", "Holding costs"],
    billCategories: ["Gas & Electric", "Council Tax"],
    complianceRequirements: ["Building regulations", "Planning permission (if applicable)", "New home warranty (if selling)"],
    typicalUpfront: "£30,000–£150,000+",
    riskLevel: "High",
    managementIntensity: "High",
    complianceComplexity: "High",
    incomeModel: "Profit on sale (GDV minus total cost)",
    bestFitPropertyTypes: ["Below-market houses", "Auction properties", "Probate properties", "Empty properties"],
    useCase: "Active capital growth strategy. Skill and speed-dependent. Project management is critical.",
    keyMetrics: ["GDV", "Total cost", "Gross profit", "ROI", "Programme length"],
  },
]

export function getProfileByKey(key: string): PlanningProfile | undefined {
  return PLANNING_PROFILES.find((p) => p.key === key)
}

export const PROFILE_GROUPS: { key: ProfileGroup; label: string; colour: string }[] = [
  { key: "residential_rental",  label: "Residential Rental",      colour: "#7C3AED" },
  { key: "short_stay",          label: "Short-Stay & Flexible",    colour: "#F59E0B" },
  { key: "lease_managed",       label: "Lease & Managed Models",   colour: "#2563EB" },
  { key: "commercial_mixed",    label: "Commercial & Mixed",        colour: "#64748B" },
  { key: "capital_strategy",    label: "Capital Strategy",          colour: "#059669" },
]
