import type { Metadata } from "next"
import LegalLayout from "@/components/marketing/LegalLayout"

export const metadata: Metadata = {
  title: "AI Disclaimer | Propvora",
  description: "Propvora AI Copilot disclaimer — what the AI does and doesn't do, accuracy limitations, and the human-approval requirement.",
}

export default function AiDisclaimerPage() {
  return (
    <LegalLayout title="AI Copilot Disclaimer" lastUpdated="2 June 2025">
      <div className="p-4 rounded-xl bg-amber-50 border border-amber-300 text-amber-900 text-sm mb-8">
        <strong>Important:</strong> Propvora AI Copilot is a productivity assistance tool. It does not provide regulated financial advice, legal advice, property investment advice, or valuation services. All AI outputs must be reviewed by you before use, and professional advice should be sought for significant decisions.
      </div>

      <Section num="1" title="What the AI Copilot Is">
        <p>
          The Propvora AI Copilot is an artificial intelligence assistant integrated into your Propvora workspace. It is powered by large language model technology and is designed to help you work more efficiently within the platform by:
        </p>
        <ul>
          <li>Analysing data within your workspace and surfacing relevant insights</li>
          <li>Answering questions about your properties, finances, and operational data</li>
          <li>Drafting documents, emails, and communications for your review</li>
          <li>Suggesting actions and next steps based on your workspace context</li>
          <li>Helping you think through deals and scenarios using your own data</li>
          <li>Summarising information from multiple parts of your workspace</li>
        </ul>
        <p>
          The AI Copilot has access to your workspace data (properties, contacts, financial records, documents) so it can provide contextually relevant assistance. This access is limited to your workspace and is not shared with other users.
        </p>
      </Section>

      <Section num="2" title="What the AI Copilot Does NOT Do">
        <p>
          The AI Copilot is explicitly not and does not provide:
        </p>

        <h3>No Financial Advice</h3>
        <p>
          The AI Copilot does not provide regulated financial advice as defined under the Financial Services and Markets Act 2000 (FSMA). It does not provide advice on investments, mortgages, insurance, pension products, or any other regulated financial product. While it may help you model numbers or summarise financial data, this is not financial advice.
        </p>
        <p>
          If you are making significant financial decisions — including property acquisitions, mortgage decisions, or investment restructuring — you must consult a regulated financial adviser, independent financial adviser (IFA), or qualified mortgage broker.
        </p>

        <h3>No Legal Advice</h3>
        <p>
          The AI Copilot does not provide legal advice. It may draft communications or documents, but these are templates for your review only and do not constitute legal advice. For tenancy legal matters, eviction procedures, contract disputes, or regulatory compliance questions, you must consult a qualified solicitor or legal adviser.
        </p>

        <h3>No Property Valuation</h3>
        <p>
          The AI Copilot does not provide RICS-compliant property valuations or market value assessments. Any figures it references are informational only and should not be relied upon for purchase, sale, or lending purposes.
        </p>

        <h3>No Tax Advice</h3>
        <p>
          The AI Copilot does not provide tax advice. It may help you organise financial data for your accountant, but it does not provide guidance on tax planning, tax liability, or compliance with HMRC requirements. Consult a qualified accountant or tax adviser.
        </p>

        <h3>No Compliance Guarantee</h3>
        <p>
          The AI Copilot does not guarantee that any content it generates, actions it suggests, or analyses it produces comply with current UK property law, housing regulations, or licensing requirements. These change frequently. You are responsible for your own regulatory compliance.
        </p>
      </Section>

      <Section num="3" title="Human Approval Requirement">
        <p>
          The Propvora AI Copilot operates on a strict human-approval model:
        </p>
        <ul>
          <li><strong>No autonomous actions:</strong> The AI Copilot cannot take actions in your workspace without your explicit approval. It can propose actions — you must approve them.</li>
          <li><strong>Review before use:</strong> Any document, communication, or analysis generated by the AI must be reviewed by you before it is used, sent, or acted upon.</li>
          <li><strong>Approval logs:</strong> All AI-suggested actions that you approve are recorded in the AI audit log for your review.</li>
          <li><strong>Revocable:</strong> You can dismiss any AI suggestion without it taking effect.</li>
        </ul>
        <p>
          You are responsible for reviewing all AI outputs before acting on them, just as you would review any document generated by an assistant.
        </p>
      </Section>

      <Section num="4" title="Accuracy and Reliability">
        <p>
          Large language models can produce incorrect, outdated, or misleading outputs. This is a known limitation of the technology. Propvora does not guarantee the accuracy, completeness, or correctness of any AI Copilot output.
        </p>
        <ul>
          <li>AI responses may contain factual errors or &ldquo;hallucinations&rdquo; (plausible-sounding but incorrect information)</li>
          <li>The AI&rsquo;s knowledge of current UK property law, regulations, and market conditions may be out of date</li>
          <li>Financial calculations suggested by the AI should be independently verified</li>
          <li>The AI&rsquo;s analysis of your workspace data is only as accurate as the data you have entered</li>
          <li>If the AI gives a figure that seems surprising, verify it from source data before relying on it</li>
        </ul>
        <p>
          The AI Copilot is a productivity tool, not an oracle. Use your professional judgement.
        </p>
      </Section>

      <Section num="5" title="Data Usage for AI Processing">
        <p>
          When you use the AI Copilot, the following data may be sent to our AI provider (OpenAI) for processing:
        </p>
        <ul>
          <li>Your query or prompt</li>
          <li>Relevant workspace context (property summaries, financial totals, task lists) as required to answer your query</li>
          <li>Workspace context is provided in summarised or anonymised form where possible — raw tenant personal data is not included unless you explicitly reference it in your query</li>
        </ul>
        <p>
          This processing is governed by our Data Processing Agreement with OpenAI, which includes appropriate data protection obligations. OpenAI is not permitted to use this data to train its models under our enterprise agreement. Full details are in our Privacy Policy.
        </p>
      </Section>

      <Section num="6" title="Queries and Usage Limits">
        <p>
          AI Copilot usage is subject to query limits based on your subscription plan (100 queries/month on Pro, 500 queries/month on Business). Query history is retained for 90 days in your AI audit log. Additional query packs are available as an add-on.
        </p>
      </Section>

      <Section num="7" title="If in Doubt, Consult a Professional">
        <p>
          Property investment and management involves significant financial, legal, and regulatory complexity. The AI Copilot is designed to help you work more efficiently — not to replace professional advice.
        </p>
        <p>
          For matters involving:
        </p>
        <ul>
          <li><strong>Property acquisition decisions</strong> — consult a property solicitor and independent financial adviser</li>
          <li><strong>Tenancy disputes or evictions</strong> — consult a specialist housing solicitor</li>
          <li><strong>Tax and accounting</strong> — consult a qualified accountant</li>
          <li><strong>HMO licensing and compliance</strong> — consult your local authority and a compliance specialist</li>
          <li><strong>Mortgage decisions</strong> — consult a qualified mortgage broker</li>
        </ul>
        <p>
          When in doubt, consult a qualified professional. Propvora is your operations tool, not your adviser.
        </p>
      </Section>

      <Section num="8" title="Contact">
        <p>
          Questions about the AI Copilot or this disclaimer: <a href="mailto:hello@propvora.com">hello@propvora.com</a>
        </p>
      </Section>
    </LegalLayout>
  )
}

function Section({ num, title, children }: { num: string; title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="text-xl font-bold text-slate-900 mb-4 flex items-baseline gap-2">
        <span className="text-blue-600 text-base font-bold">{num}.</span>
        {title}
      </h2>
      <div className="space-y-4 text-slate-700 leading-relaxed text-sm [&_a]:text-blue-600 [&_a:hover]:text-blue-700 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_strong]:font-semibold [&_strong]:text-slate-900 [&_h3]:font-semibold [&_h3]:text-slate-900 [&_h3]:mt-4 [&_h3]:mb-2">
        {children}
      </div>
    </div>
  )
}
