// Default seeded workflow for new automations.
// Represents: "Compliance item due soon" → condition → TRUE/FALSE branches.

import type { Node, Edge } from "@xyflow/react"
import type { CanvasFlowNodeData } from "./types"

export function buildSeedWorkflow(): { nodes: Node<CanvasFlowNodeData>[]; edges: Edge[] } {
  const nodes: Node<CanvasFlowNodeData>[] = [
    {
      id: "trigger-1",
      type: "automationNode",
      position: { x: 360, y: 60 },
      data: {
        nodeKey: "trigger-1",
        nodeType: "compliance.expiring",
        category: "trigger",
        label: "Compliance item due soon",
        description: "Fires when a certificate or safety item is expiring",
        config: { within_days: 30 },
        validationStatus: "valid",
        requiresApproval: true,
        risk: "high",
      },
    },
    {
      id: "condition-1",
      type: "automationNode",
      position: { x: 360, y: 220 },
      data: {
        nodeKey: "condition-1",
        nodeType: "condition.if_else",
        category: "condition",
        label: "Certificate type & days ahead",
        description: "Check certificate type and how far ahead the due date is",
        config: { field: "within_days", op: "lte", value: "14" },
        validationStatus: "valid",
        requiresApproval: false,
        risk: "low",
      },
    },
    // TRUE branch
    {
      id: "action-create-task",
      type: "automationNode",
      position: { x: 100, y: 420 },
      data: {
        nodeKey: "action-create-task",
        nodeType: "action.create_task",
        category: "action",
        label: "Create compliance task",
        description: "Creates an urgent compliance renewal task",
        config: { title: "Renew: {{summary}}", priority: "urgent", due_in_days: 7 },
        validationStatus: "valid",
        requiresApproval: false,
        risk: "low",
      },
    },
    {
      id: "comm-notify",
      type: "automationNode",
      position: { x: 100, y: 590 },
      data: {
        nodeKey: "comm-notify",
        nodeType: "comm.internal_notification",
        category: "communication",
        label: "Send notification",
        description: "Alerts the property manager about the expiring certificate",
        config: { title: "Compliance alert: {{summary}}", severity: "warning" },
        validationStatus: "valid",
        requiresApproval: false,
        risk: "low",
      },
    },
    {
      id: "approval-manager",
      type: "automationNode",
      position: { x: 100, y: 760 },
      data: {
        nodeKey: "approval-manager",
        nodeType: "approval.request_human",
        category: "approval",
        label: "Manager approval",
        description: "Requires a manager to approve the compliance action",
        config: { title: "Approve compliance renewal", sla_hours: 24 },
        validationStatus: "valid",
        requiresApproval: true,
        risk: "medium",
      },
    },
    {
      id: "action-update-record",
      type: "automationNode",
      position: { x: 100, y: 930 },
      data: {
        nodeKey: "action-update-record",
        nodeType: "action.update_record",
        category: "action",
        label: "Update compliance record",
        description: "Marks the compliance item as being actioned",
        config: { field: "status", value: "actioning" },
        validationStatus: "valid",
        requiresApproval: false,
        risk: "medium",
      },
    },
    // FALSE branch
    {
      id: "action-add-note",
      type: "automationNode",
      position: { x: 620, y: 420 },
      data: {
        nodeKey: "action-add-note",
        nodeType: "action.add_note",
        category: "action",
        label: "Log event",
        description: "Logs the compliance check outcome to the record timeline",
        config: { body: "Compliance check: {{summary}} — within acceptable range." },
        validationStatus: "valid",
        requiresApproval: false,
        risk: "low",
      },
    },
    {
      id: "webhook-out",
      type: "automationNode",
      position: { x: 620, y: 590 },
      data: {
        nodeKey: "webhook-out",
        nodeType: "webhook.outgoing",
        category: "webhook",
        label: "Webhook",
        description: "Posts a signed event to the configured endpoint",
        config: { endpoint_id: "" },
        validationStatus: "warning",
        requiresApproval: false,
        risk: "medium",
      },
    },
    {
      id: "action-invoice",
      type: "automationNode",
      position: { x: 620, y: 760 },
      data: {
        nodeKey: "action-invoice",
        nodeType: "action.create_invoice_draft",
        category: "action",
        label: "Create invoice reminder",
        description: "Drafts a renewal invoice for review",
        config: { reference: "Compliance renewal: {{summary}}" },
        validationStatus: "valid",
        requiresApproval: true,
        risk: "medium",
      },
    },
    {
      id: "end-success",
      type: "automationNode",
      position: { x: 360, y: 1100 },
      data: {
        nodeKey: "end-success",
        nodeType: "end.success",
        category: "end",
        label: "Audit log & end",
        description: "Logs the automation run to the audit trail and completes",
        config: {},
        validationStatus: "valid",
        requiresApproval: false,
        risk: "low",
      },
    },
  ]

  const edges: Edge[] = [
    {
      id: "e-trigger-condition",
      source: "trigger-1",
      target: "condition-1",
      type: "smoothstep",
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    },
    {
      id: "e-condition-true",
      source: "condition-1",
      target: "action-create-task",
      label: "TRUE",
      type: "smoothstep",
      style: { stroke: "#10b981", strokeWidth: 2 },
      labelStyle: { fill: "#10b981", fontWeight: 600, fontSize: 11 },
      labelBgStyle: { fill: "#f0fdf4" },
    },
    {
      id: "e-condition-false",
      source: "condition-1",
      target: "action-add-note",
      label: "FALSE",
      type: "smoothstep",
      style: { stroke: "#f59e0b", strokeWidth: 2 },
      labelStyle: { fill: "#d97706", fontWeight: 600, fontSize: 11 },
      labelBgStyle: { fill: "#fffbeb" },
    },
    {
      id: "e-task-notify",
      source: "action-create-task",
      target: "comm-notify",
      type: "smoothstep",
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    },
    {
      id: "e-notify-approval",
      source: "comm-notify",
      target: "approval-manager",
      type: "smoothstep",
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    },
    {
      id: "e-approval-update",
      source: "approval-manager",
      target: "action-update-record",
      label: "Approved",
      type: "smoothstep",
      style: { stroke: "#6366f1", strokeWidth: 2 },
      labelStyle: { fill: "#6366f1", fontWeight: 600, fontSize: 11 },
      labelBgStyle: { fill: "#eef2ff" },
    },
    {
      id: "e-note-webhook",
      source: "action-add-note",
      target: "webhook-out",
      type: "smoothstep",
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    },
    {
      id: "e-webhook-invoice",
      source: "webhook-out",
      target: "action-invoice",
      type: "smoothstep",
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    },
    {
      id: "e-update-end",
      source: "action-update-record",
      target: "end-success",
      type: "smoothstep",
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    },
    {
      id: "e-invoice-end",
      source: "action-invoice",
      target: "end-success",
      type: "smoothstep",
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    },
  ]

  return { nodes, edges }
}
