import "server-only"
import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import type { SupabaseClient } from "@supabase/supabase-js"
import { resolveModelChain, gatewayComplete } from "./gateway"
import { orderChainForRole } from "./routing"
import { createAdminClient } from "@/lib/supabase/admin"
import { uploadToR2, buildKey, fileViewUrl } from "@/lib/r2"

// ============================================================================
// Document generation — produce a real, grounded PDF (report / letter / notice)
// from workspace context, store it in R2, and link it into the documents table.
//
// The model generates the BODY text (compliant routing — agentic tier); pdf-lib
// renders it to a branded PDF; uploadToR2 stores it; a documents row links it so
// it appears in the Documents section. Audited + credited by the tool registry
// (doc.generate → Intelligence class). No external service beyond the model +
// R2 (both already configured).
// ============================================================================

const DOC_SYSTEM: Record<string, string> = {
  report:
    "You are a senior UK property operator writing a concise, professional report. Use clear headings and short paragraphs. British English. Ground every statement in the supplied context; never invent figures, names or dates.",
  letter:
    "You are drafting a professional UK property-management letter. Include a clear subject line, a polite, precise body, and a sign-off. British English. Never invent facts; leave a clearly-marked [placeholder] only where a detail is genuinely unknown.",
  notice:
    "You are drafting a formal UK property notice. Use precise, neutral language and a clear structure. British English. Include a prominent line stating this is a draft for review and is not legal advice. Never invent dates or legal facts.",
}

export interface GenerateDocArgs {
  workspaceId: string
  userId: string | null
  kind: string // 'report' | 'letter' | 'notice' | ...
  title: string
  instructions: string
  propertyId?: string | null
}

export interface GenerateDocResult {
  documentId: string | null
  key: string
  url: string
  model: string
  bytes: number
}

/** Word-wrap + paginate `body` into a simple branded PDF; returns the bytes. */
async function renderPdf(title: string, body: string): Promise<Uint8Array> {
  const pdf = await PDFDocument.create()
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)

  const W = 595.28, H = 841.89 // A4
  const margin = 56
  const maxW = W - margin * 2
  const brand = rgb(0.16, 0.16, 0.55) // Propvora indigo/slate

  let page = pdf.addPage([W, H])
  let y = H - margin

  // Header band
  page.drawRectangle({ x: 0, y: H - 8, width: W, height: 8, color: brand })
  page.drawText("Propvora", { x: margin, y: y, size: 10, font: bold, color: brand })
  y -= 24
  // Title (wrapped, bold)
  for (const line of wrap(title, bold, 18, maxW)) {
    page.drawText(line, { x: margin, y, size: 18, font: bold, color: rgb(0.1, 0.1, 0.1) })
    y -= 24
  }
  y -= 8

  const draw = (text: string, size: number, f = font) => {
    for (const line of wrap(text, f, size, maxW)) {
      if (y < margin + 24) {
        page = pdf.addPage([W, H])
        y = H - margin
      }
      page.drawText(line, { x: margin, y, size, font: f, color: rgb(0.15, 0.15, 0.15) })
      y -= size * 1.5
    }
  }

  for (const para of body.split(/\n\n+/)) {
    const trimmed = para.trim()
    if (!trimmed) continue
    // A short ALL-CAPS / heading-ish line renders bold.
    const isHeading = trimmed.length < 64 && !/[.!?]$/.test(trimmed) && trimmed.split("\n").length === 1
    draw(trimmed, isHeading ? 12.5 : 11, isHeading ? bold : font)
    y -= 6
  }

  // Footer disclaimer
  if (y < margin + 40) { page = pdf.addPage([W, H]); y = H - margin }
  page.drawText("Generated by Propvora Copilot — review before use. Not legal or financial advice.", {
    x: margin, y: margin - 24, size: 8, font, color: rgb(0.5, 0.5, 0.5),
  })

  return pdf.save()
}

function wrap(text: string, font: { widthOfTextAtSize: (t: string, s: number) => number }, size: number, maxW: number): string[] {
  const out: string[] = []
  for (const rawLine of text.split("\n")) {
    const words = rawLine.split(/\s+/).filter(Boolean)
    let line = ""
    for (const w of words) {
      const test = line ? `${line} ${w}` : w
      if (font.widthOfTextAtSize(test, size) > maxW && line) {
        out.push(line)
        line = w
      } else {
        line = test
      }
    }
    out.push(line)
  }
  return out.length ? out : [""]
}

/**
 * Generate a document: model → PDF → R2 → documents row. Returns the new
 * document id + an authed view URL. Throws on a hard failure (the tool registry
 * captures it as a failed run + audit row).
 */
export async function generateDocument(
  supabase: SupabaseClient,
  args: GenerateDocArgs
): Promise<GenerateDocResult> {
  const system = DOC_SYSTEM[args.kind] ?? DOC_SYSTEM.report
  const chain = orderChainForRole(await resolveModelChain(supabase), "agentic")
  const gen = await gatewayComplete(chain, {
    maxTokens: 1500,
    temperature: 0.4,
    messages: [
      { role: "system", content: system },
      { role: "user", content: `Title: ${args.title}\n\n${args.instructions}` },
    ],
  })
  if (!gen.text.trim()) throw new Error("The model returned no content for this document.")

  const bytes = await renderPdf(args.title, gen.text)
  const safe = args.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase().slice(0, 48) || "document"
  const key = buildKey(args.workspaceId, "ai-generated", `${safe}.pdf`)
  await uploadToR2(key, bytes, "application/pdf")

  let documentId: string | null = null
  try {
    const admin = createAdminClient()
    const { data } = await admin
      .from("documents")
      .insert({
        workspace_id: args.workspaceId,
        property_id: args.propertyId ?? null,
        name: args.title,
        type: args.kind,
        category: "ai_generated",
        mime_type: "application/pdf",
        size_bytes: bytes.length,
        r2_key: key,
        r2_bucket: process.env.R2_BUCKET ?? "",
        status: "ready",
        created_by: args.userId,
        demo: false,
        metadata: { generated_by: "copilot", model: gen.model },
      })
      .select("id")
      .single()
    documentId = (data as { id?: string } | null)?.id ?? null
  } catch {
    /* document stored in R2 even if the link row fails — non-fatal */
  }

  return { documentId, key, url: fileViewUrl(key), model: gen.model, bytes: bytes.length }
}
