import type { PublicStay, PublicProvider, PublicServiceOffer, PublicEmergencyService, PublicLongTermRental } from './types'

// NOTE: Images use Unsplash CDN URLs for development/demo only.
// Replace with real CDN assets before production.

export const SEED_STAYS: PublicStay[] = [
  {
    id: '1',
    slug: 'luxury-2-bed-apartment-shoreditch',
    title: 'Luxury 2-Bed Apartment, Shoreditch',
    stayType: 'Entire home',
    location: 'Shoreditch, London E2',
    city: 'London',
    postcode: 'E2',
    beds: 2,
    bathrooms: 2,
    guests: 4,
    bedrooms: 2,
    rating: 4.9,
    reviewCount: 128,
    pricePerNight: 14500,
    cleaningFee: 4500,
    serviceFee: 2300,
    taxes: 1700,
    verified: true,
    instantBook: true,
    freeCancellation: true,
    shortLets: true,
    longStays: false,
    petsAllowed: false,
    hostName: 'Manchester Stays',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 128,
    hostRating: 4.9,
    hostReviews: 1248,
    hostResponseTime: '20 mins',
    heroImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    lat: 51.5239,
    lng: -0.0693,
    amenities: ['Fast Wi-Fi 175Mbps', 'Smart TV with Netflix', 'Fully equipped kitchen', 'Washer & dryer', 'Private balcony', 'Central heating'],
    badges: ['bills-included', 'fast-wifi', 'weekly-cleaning'],
    description: 'A beautifully designed 2-bedroom apartment in the heart of Shoreditch. This stunning space features exposed brick walls, high ceilings and premium finishes throughout. Perfect for professionals, couples or small families seeking a premium base in East London.',
    highlights: ['Entire home', 'Self check-in', 'Great location', 'Fast Wi-Fi'],
    houseRules: ['No smoking', 'No parties or events', 'Check-in: 3PM', 'Check-out: 11AM', 'Pets not allowed'],
    cancellationPolicy: 'Free cancellation before 48 hours. After that, 50% refund for cancellations made at least 7 days before check-in.',
    rooms: [
      { name: 'Bedroom 1', description: 'King-size bed, en-suite bathroom, built-in wardrobe' },
      { name: 'Bedroom 2', description: 'Queen-size bed, balcony access, built-in wardrobe' },
      { name: 'Living room', description: 'Sofa bed (sleeps 2), Smart TV, open plan' },
      { name: 'Bathrooms', description: '2 full bathrooms, rainfall shower, luxury toiletries' },
    ],
  },
  {
    id: '2',
    slug: 'modern-studio-spinningfields',
    title: 'Modern Studio, Spinningfields',
    stayType: 'Studio',
    location: 'Spinningfields, Manchester M3',
    city: 'Manchester',
    postcode: 'M3',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.7,
    reviewCount: 86,
    pricePerNight: 8500,
    cleaningFee: 2500,
    serviceFee: 1200,
    taxes: 900,
    verified: true,
    instantBook: true,
    freeCancellation: false,
    shortLets: true,
    longStays: false,
    petsAllowed: false,
    hostName: 'City Stays MCR',
    hostAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 45,
    hostRating: 4.7,
    hostReviews: 623,
    hostResponseTime: '15 mins',
    heroImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    lat: 53.4793,
    lng: -2.2529,
    amenities: ['Fast Wi-Fi', 'Smart TV', 'Kitchen', 'Gym access', 'Concierge'],
    badges: ['bills-included'],
    description: "Sleek studio apartment in the heart of Manchester's financial district. Walking distance to Deansgate, Salford Quays and top restaurants.",
    highlights: ['Self check-in', 'Great location', 'Fast Wi-Fi', 'Gym access'],
    rooms: [{ name: 'Studio', description: 'Open plan living, double bed, fully equipped kitchen' }],
  },
  {
    id: '3',
    slug: 'charming-cottage-didsbury',
    title: 'Charming 3-Bed Cottage, Didsbury',
    stayType: 'Entire home',
    location: 'Didsbury, Manchester M20',
    city: 'Manchester',
    postcode: 'M20',
    beds: 3,
    bathrooms: 2,
    guests: 6,
    bedrooms: 3,
    rating: 4.8,
    reviewCount: 203,
    pricePerNight: 12000,
    cleaningFee: 5500,
    serviceFee: 1800,
    taxes: 1400,
    verified: true,
    instantBook: false,
    freeCancellation: true,
    shortLets: false,
    longStays: true,
    petsAllowed: true,
    hostName: 'Didsbury Homes',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 8,
    hostRating: 4.8,
    hostReviews: 412,
    hostResponseTime: '1 hour',
    heroImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    lat: 53.4126,
    lng: -2.2297,
    amenities: ['Garden', 'Parking', 'Wi-Fi', 'Washer', 'Dishwasher', 'Pets welcome'],
    badges: ['pet-friendly', 'long-stay'],
    description: 'Beautiful Victorian cottage with a private garden in the leafy suburb of Didsbury. Perfect for families or groups looking for a longer stay.',
    rooms: [
      { name: 'Master bedroom', description: 'King bed, en-suite' },
      { name: 'Bedroom 2', description: 'Double bed' },
      { name: 'Bedroom 3', description: 'Twin beds' },
    ],
  },
  {
    id: '4',
    slug: 'city-centre-penthouse-northern-quarter',
    title: 'City Centre Penthouse, Northern Quarter',
    stayType: 'Penthouse',
    location: 'Northern Quarter, Manchester M4',
    city: 'Manchester',
    postcode: 'M4',
    beds: 2,
    bathrooms: 2,
    guests: 4,
    bedrooms: 2,
    rating: 5.0,
    reviewCount: 47,
    pricePerNight: 18000,
    cleaningFee: 6000,
    serviceFee: 2800,
    taxes: 2100,
    verified: true,
    instantBook: true,
    freeCancellation: true,
    shortLets: true,
    longStays: false,
    petsAllowed: false,
    hostName: 'Northern Quarter Stays',
    hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 23,
    hostRating: 5.0,
    hostReviews: 189,
    hostResponseTime: '10 mins',
    heroImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    lat: 53.4841,
    lng: -2.2354,
    amenities: ['Panoramic views', 'Roof terrace', 'Fast Wi-Fi', 'Smart home', 'Concierge'],
    badges: ['premium', 'new-listing'],
    description: 'Stunning penthouse apartment with panoramic views over Manchester city centre. Roof terrace perfect for entertaining.',
    rooms: [
      { name: 'Master suite', description: 'Super king bed, en-suite with freestanding bath' },
      { name: 'Bedroom 2', description: 'King bed, city views' },
    ],
  },
  {
    id: '5',
    slug: 'private-room-salford-quays',
    title: 'Private Room, Salford Quays',
    stayType: 'Private room',
    location: 'Salford Quays, Salford M50',
    city: 'Salford',
    postcode: 'M50',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.6,
    reviewCount: 134,
    pricePerNight: 4500,
    cleaningFee: 1500,
    serviceFee: 700,
    taxes: 500,
    verified: true,
    instantBook: true,
    freeCancellation: true,
    shortLets: true,
    longStays: true,
    petsAllowed: false,
    hostName: 'Quays Rentals',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 4,
    hostRating: 4.6,
    hostReviews: 267,
    hostResponseTime: '30 mins',
    heroImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    gallery: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'],
    lat: 53.4726,
    lng: -2.2979,
    amenities: ['Wi-Fi', 'Shared kitchen', 'MediaCity access', 'Parking'],
    badges: [],
    description: 'Bright private room with waterfront views near MediaCity UK. Great transport links into Manchester city centre.',
  },
  {
    id: '6',
    slug: 'luxury-1-bed-chorlton',
    title: 'Luxury 1-Bed Flat, Chorlton',
    stayType: 'Entire home',
    location: 'Chorlton, Manchester M21',
    city: 'Manchester',
    postcode: 'M21',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.8,
    reviewCount: 91,
    pricePerNight: 7800,
    cleaningFee: 2000,
    serviceFee: 1100,
    taxes: 800,
    verified: true,
    instantBook: false,
    freeCancellation: true,
    shortLets: true,
    longStays: true,
    petsAllowed: true,
    hostName: 'Chorlton Lets',
    hostAvatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 6,
    hostRating: 4.8,
    hostReviews: 341,
    hostResponseTime: '45 mins',
    heroImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    gallery: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800'],
    lat: 53.4407,
    lng: -2.2770,
    amenities: ['Garden', 'Wi-Fi', 'Washer', 'Pets OK', 'Quiet street'],
    badges: ['pet-friendly'],
  },
  {
    id: '7',
    slug: 'serviced-apartment-manchester-city',
    title: 'Serviced Apartment, Manchester City',
    stayType: 'Entire home',
    location: 'City Centre, Manchester M1',
    city: 'Manchester',
    postcode: 'M1',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.7,
    reviewCount: 312,
    pricePerNight: 9500,
    cleaningFee: 2500,
    serviceFee: 1400,
    taxes: 1000,
    verified: true,
    instantBook: true,
    freeCancellation: false,
    shortLets: true,
    longStays: true,
    petsAllowed: false,
    hostName: 'Manchester Stays',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 128,
    hostRating: 4.9,
    hostReviews: 1248,
    hostResponseTime: '20 mins',
    heroImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    gallery: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    lat: 53.4808,
    lng: -2.2426,
    amenities: ['Wi-Fi', 'Gym', 'Concierge', 'Smart TV', 'Housekeeping'],
    badges: ['bills-included', 'weekly-cleaning'],
  },
  {
    id: '8',
    slug: 'hmo-room-fallowfield',
    title: 'Furnished Room, Fallowfield',
    stayType: 'Private room',
    location: 'Fallowfield, Manchester M14',
    city: 'Manchester',
    postcode: 'M14',
    beds: 1,
    bathrooms: 1,
    guests: 1,
    bedrooms: 1,
    rating: 4.4,
    reviewCount: 67,
    pricePerNight: 3500,
    cleaningFee: 1000,
    serviceFee: 500,
    taxes: 400,
    verified: false,
    instantBook: true,
    freeCancellation: true,
    shortLets: false,
    longStays: true,
    petsAllowed: false,
    hostName: 'Student Stays MCR',
    hostAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 12,
    hostRating: 4.4,
    hostReviews: 234,
    hostResponseTime: '2 hours',
    heroImage: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
    gallery: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800'],
    lat: 53.4440,
    lng: -2.2169,
    amenities: ['Wi-Fi', 'Bills included', 'Shared kitchen', 'Laundry'],
    badges: ['bills-included', 'long-stay'],
  },
]

export const SEED_PROVIDERS: PublicProvider[] = [
  {
    id: '1',
    slug: 'citywide-plumbing-heating',
    companyName: 'Citywide Plumbing & Heating',
    trade: 'Plumbing & Heating',
    location: 'Greater Manchester, UK',
    city: 'Manchester',
    rating: 4.8,
    reviewCount: 128,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£5M',
    teamSize: 48,
    jobsDone: 2450,
    yearsActive: 12,
    responseTime: '28 mins',
    fromPrice: 8500,
    heroImage: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800',
    logo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    certifications: ['Gas Safe', 'NICEIC', 'DBS Verified', 'CHAS'],
    coverageRadius: 50,
    coverageCities: ['Manchester', 'Salford', 'Stockport', 'Bury', 'Oldham', 'Rochdale'],
    featured: true,
    emergency24h: true,
    gasSafe: '556789',
    description: "Greater Manchester's leading plumbing and heating specialists with over 12 years of experience.",
    services: ['Boiler installation', 'Boiler repair', 'Central heating', 'Emergency plumbing', 'Bathroom installation', 'Gas safety certificates'],
    faqs: [
      { q: 'Do you offer emergency call-outs?', a: 'Yes, 24/7 across Greater Manchester with a typical arrival time of 28 minutes.' },
      { q: 'Are you Gas Safe registered?', a: 'Yes, Gas Safe No. 556789.' },
    ],
    recentWork: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400',
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    ],
    teamMembers: [
      { name: 'James Wilson', role: 'Lead Engineer', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face' },
      { name: 'Sarah Chen', role: 'Senior Plumber', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face' },
      { name: 'Mike Patel', role: 'Gas Engineer', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face' },
    ],
    lat: 53.4808,
    lng: -2.2426,
    initials: 'CPH',
    pinColor: '#2563eb',
  },
  {
    id: '2',
    slug: 'manchester-electrical',
    companyName: 'Manchester Electrical Solutions',
    trade: 'Electrical Services',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.9,
    reviewCount: 203,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£2M',
    teamSize: 22,
    jobsDone: 1820,
    yearsActive: 8,
    responseTime: '35 mins',
    fromPrice: 7500,
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    certifications: ['NICEIC', 'Part P', 'DBS Verified'],
    coverageRadius: 30,
    coverageCities: ['Manchester', 'Salford', 'Trafford', 'Tameside'],
    featured: true,
    emergency24h: true,
    niceic: true,
    description: 'NICEIC-approved electrical contractors serving residential and commercial clients across Greater Manchester.',
    lat: 53.4800,
    lng: -2.2350,
    initials: 'ME',
    pinColor: '#7c3aed',
  },
  {
    id: '3',
    slug: 'northern-waste-management',
    companyName: 'Northern Waste Management',
    trade: 'Waste Removal & Clearance',
    location: 'Salford, UK',
    city: 'Salford',
    rating: 4.6,
    reviewCount: 89,
    proBadge: false,
    vetted: true,
    insured: true,
    insuranceAmount: '£1M',
    teamSize: 12,
    jobsDone: 480,
    yearsActive: 6,
    responseTime: '30 mins',
    fromPrice: 6500,
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    logo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    certifications: ['Waste Carrier Licence', 'DBS'],
    coverageRadius: 25,
    coverageCities: ['Salford', 'Manchester', 'Eccles', 'Worsley'],
    featured: false,
    emergency24h: false,
    lat: 53.4900,
    lng: -2.2979,
    initials: 'NW',
    pinColor: '#059669',
  },
  {
    id: '4',
    slug: 'heritage-property-preservation',
    companyName: 'Heritage Property Preservation',
    trade: 'Building & Restoration',
    location: 'Stockport, UK',
    city: 'Stockport',
    rating: 4.7,
    reviewCount: 156,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£10M',
    teamSize: 35,
    jobsDone: 890,
    yearsActive: 18,
    responseTime: '2 hours',
    fromPrice: 15000,
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    logo: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop&crop=face',
    certifications: ['NHBC', 'CHAS', 'ISO 9001'],
    coverageRadius: 40,
    coverageCities: ['Stockport', 'Manchester', 'Cheadle', 'Macclesfield'],
    featured: true,
    emergency24h: false,
    lat: 53.4059,
    lng: -2.1575,
    initials: 'HPP',
    pinColor: '#d97706',
  },
  {
    id: '5',
    slug: 'bright-cleaning-services',
    companyName: 'Bright Cleaning Services',
    trade: 'Professional Cleaning',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.8,
    reviewCount: 445,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£1M',
    teamSize: 64,
    jobsDone: 5200,
    yearsActive: 9,
    responseTime: '15 mins',
    fromPrice: 4500,
    heroImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    logo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    certifications: ['BICSc', 'DBS', 'ISO 14001'],
    coverageRadius: 20,
    coverageCities: ['Manchester', 'Salford', 'Trafford'],
    featured: false,
    emergency24h: false,
    lat: 53.4750,
    lng: -2.2500,
    initials: 'BCS',
    pinColor: '#0891b2',
  },
  {
    id: '6',
    slug: 'premier-property-maintenance',
    companyName: 'Premier Property Maintenance',
    trade: 'General Maintenance & Repairs',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.5,
    reviewCount: 78,
    proBadge: false,
    vetted: true,
    insured: true,
    insuranceAmount: '£2M',
    teamSize: 8,
    jobsDone: 320,
    yearsActive: 4,
    responseTime: '45 mins',
    fromPrice: 5500,
    heroImage: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800',
    logo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face',
    certifications: ['DBS'],
    coverageRadius: 15,
    coverageCities: ['Manchester', 'Salford'],
    featured: false,
    emergency24h: false,
    lat: 53.4820,
    lng: -2.2380,
    initials: 'PPM',
    pinColor: '#dc2626',
  },
  {
    id: '7',
    slug: 'green-thumb-gardens',
    companyName: 'Green Thumb Gardens',
    trade: 'Landscaping & Gardening',
    location: 'South Manchester, UK',
    city: 'Manchester',
    rating: 4.7,
    reviewCount: 112,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£1M',
    teamSize: 18,
    jobsDone: 780,
    yearsActive: 7,
    responseTime: '1 hour',
    fromPrice: 4500,
    heroImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    logo: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop&crop=face',
    certifications: ['RHS Qualified', 'DBS'],
    coverageRadius: 20,
    coverageCities: ['Manchester', 'Didsbury', 'Chorlton', 'Stockport'],
    featured: false,
    emergency24h: false,
    description: 'Professional landscaping and garden maintenance for residential and commercial properties.',
    lat: 53.4300,
    lng: -2.2400,
    initials: 'GTG',
    pinColor: '#16a34a',
  },
  {
    id: '8',
    slug: 'northern-roofing-specialists',
    companyName: 'Northern Roofing Specialists',
    trade: 'Roofing & Guttering',
    location: 'Greater Manchester, UK',
    city: 'Manchester',
    rating: 4.6,
    reviewCount: 95,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£3M',
    teamSize: 14,
    jobsDone: 560,
    yearsActive: 11,
    responseTime: '4 hours',
    fromPrice: 12000,
    heroImage: 'https://images.unsplash.com/photo-1593620659530-8614a3474f2d?w=800',
    logo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    certifications: ['NFRC', 'DBS', 'CHAS'],
    coverageRadius: 35,
    coverageCities: ['Manchester', 'Salford', 'Bury', 'Bolton', 'Wigan'],
    featured: false,
    emergency24h: true,
    description: 'NFRC-approved roofing contractors. Emergency call-outs for storm damage and leaks.',
    lat: 53.5200,
    lng: -2.2100,
    initials: 'NRS',
    pinColor: '#b45309',
  },
  {
    id: '9',
    slug: 'precision-painting-decorating',
    companyName: 'Precision Painting & Decorating',
    trade: 'Painting & Decorating',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.8,
    reviewCount: 167,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£1M',
    teamSize: 16,
    jobsDone: 1100,
    yearsActive: 9,
    responseTime: '2 hours',
    fromPrice: 5000,
    heroImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800',
    logo: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop&crop=face',
    certifications: ['PDCA', 'DBS'],
    coverageRadius: 25,
    coverageCities: ['Manchester', 'Salford', 'Trafford', 'Stockport'],
    featured: true,
    emergency24h: false,
    description: 'Award-winning painting and decorating contractors for residential and commercial properties.',
    lat: 53.4750,
    lng: -2.2600,
    initials: 'PPD',
    pinColor: '#7c3aed',
  },
  {
    id: '10',
    slug: 'metro-property-management',
    companyName: 'Metro Property Management',
    trade: 'Property Management',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.7,
    reviewCount: 234,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£5M',
    teamSize: 32,
    jobsDone: 3200,
    yearsActive: 15,
    responseTime: '20 mins',
    fromPrice: 9500,
    heroImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    logo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    certifications: ['ARLA Propertymark', 'RICS', 'DBS'],
    coverageRadius: 45,
    coverageCities: ['Manchester', 'Salford', 'Trafford', 'Stockport', 'Tameside'],
    featured: false,
    emergency24h: false,
    description: 'ARLA Propertymark-accredited property management specialists.',
    lat: 53.4808,
    lng: -2.2426,
    initials: 'MPM',
    pinColor: '#0891b2',
  },
  {
    id: '11',
    slug: 'ace-gas-heating-services',
    companyName: 'Ace Gas & Heating Services',
    trade: 'Gas & Heating',
    location: 'Leeds, UK',
    city: 'Leeds',
    rating: 4.9,
    reviewCount: 189,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£5M',
    teamSize: 20,
    jobsDone: 1560,
    yearsActive: 10,
    responseTime: '30 mins',
    fromPrice: 8000,
    heroImage: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800',
    logo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    certifications: ['Gas Safe', 'DBS', 'CHAS'],
    coverageRadius: 30,
    coverageCities: ['Leeds', 'Bradford', 'Wakefield', 'Harrogate'],
    featured: true,
    emergency24h: true,
    gasSafe: '783421',
    description: 'Gas Safe registered heating engineers covering West Yorkshire.',
    lat: 53.8008,
    lng: -1.5491,
    initials: 'AGH',
    pinColor: '#ea580c',
  },
  {
    id: '12',
    slug: 'swift-security-solutions',
    companyName: 'Swift Security Solutions',
    trade: 'Security & CCTV',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.6,
    reviewCount: 74,
    proBadge: false,
    vetted: true,
    insured: true,
    insuranceAmount: '£2M',
    teamSize: 10,
    jobsDone: 390,
    yearsActive: 5,
    responseTime: '1 hour',
    fromPrice: 7500,
    heroImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    certifications: ['SIA Licensed', 'DBS', 'NSI Gold'],
    coverageRadius: 20,
    coverageCities: ['Manchester', 'Salford', 'Trafford'],
    featured: false,
    emergency24h: false,
    description: 'SIA-licensed security installers for CCTV, access control, alarms and smart security systems.',
    lat: 53.4808,
    lng: -2.2426,
    initials: 'SSS',
    pinColor: '#1e40af',
  },
]

export const SEED_SERVICE_OFFERS: PublicServiceOffer[] = [
  {
    id: '1',
    slug: 'end-of-tenancy-deep-clean',
    title: 'End of Tenancy Deep Clean',
    subtitle: 'Move-out cleaning that gets your deposit back.',
    category: 'Cleaning',
    providerName: 'Bright Cleaning Services',
    providerSlug: 'bright-cleaning-services',
    providerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.8,
    reviewCount: 128,
    jobsDone: 200,
    location: 'West Yorkshire',
    city: 'Leeds',
    heroImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    gallery: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800'],
    basePrice: 12000,
    standardPrice: 18000,
    premiumPrice: 26000,
    duration: '3-8 hours',
    responseTime: '< 2 hours',
    nextAvailable: 'Today 2:00 PM',
    featured: true,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Full kitchen deep clean', 'All bathrooms sanitised', 'Carpets vacuumed', 'Windows cleaned'],
    tags: ['Residential', 'Tenants & Landlords', 'Flats & Houses', 'Move-out Ready'],
    packages: [
      { name: 'Basic', price: 12000, description: 'Essential clean for 1-bed properties', includes: ['Kitchen surface clean', 'Bathroom clean', 'Living areas hoovered'] },
      { name: 'Standard', price: 18000, description: 'For 2-3 bed properties — Most popular', includes: ['Kitchen deep clean', 'Bathroom sanitisation', 'Oven clean included', 'Skirting boards'] },
      { name: 'Premium', price: 26000, description: 'Deep & detailed for 3+ bed properties', includes: ['Full kitchen deep clean', 'All bathrooms deep clean', 'All windows', 'Carpet shampooing'] },
    ],
    addons: [
      { name: 'Oven deep clean', price: 4000 },
      { name: 'Carpet shampoo', price: 6000 },
    ],
    lat: 53.8008,
    lng: -1.5491,
  },
  {
    id: '2',
    slug: 'emergency-boiler-repair',
    title: 'Emergency Boiler Repair',
    subtitle: 'Same-day boiler repairs by Gas Safe engineers.',
    category: 'Plumbing',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.9,
    reviewCount: 312,
    jobsDone: 850,
    location: 'Greater Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800',
    gallery: ['https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800'],
    basePrice: 8500,
    standardPrice: 12500,
    premiumPrice: 18500,
    duration: '1-3 hours',
    responseTime: '28 mins',
    nextAvailable: 'Now',
    featured: true,
    verified: true,
    insured: true,
    urgent: true,
    deliverables: ['Fault diagnosis', 'Part replacement (if needed)', 'Safety check', 'Gas Safe certificate'],
    tags: ['Residential', 'Commercial', 'Emergency'],
    packages: [
      { name: 'Basic', price: 8500, description: 'Diagnosis and minor repair', includes: ['Boiler inspection', 'Fault diagnosis', 'Minor repair'] },
      { name: 'Standard', price: 12500, description: 'Repair including common parts', includes: ['Diagnosis', 'Common parts', 'Safety check', 'Report'] },
      { name: 'Premium', price: 18500, description: 'Full repair with Gas Safe certificate', includes: ['Full repair', 'Parts included', 'Gas Safe cert', 'Priority callback'] },
    ],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: '3',
    slug: 'electrical-safety-certificate',
    title: 'Electrical Safety Certificate (EICR)',
    subtitle: 'NICEIC-approved EICR for landlords & letting agents.',
    category: 'Electrical',
    providerName: 'Manchester Electrical Solutions',
    providerSlug: 'manchester-electrical',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.9,
    reviewCount: 203,
    jobsDone: 680,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    gallery: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
    basePrice: 9900,
    standardPrice: 13500,
    premiumPrice: 19900,
    duration: '2-4 hours',
    responseTime: '< 24 hours',
    nextAvailable: 'Tomorrow 9:00 AM',
    featured: true,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Full EICR inspection', 'Written report', 'Certificate issued', 'Remedial quote if needed'],
    tags: ['Residential', 'Landlords', 'HMO'],
    packages: [
      { name: 'Basic', price: 9900, description: '1-2 bed property EICR', includes: ['Full inspection', 'EICR certificate', 'Written report'] },
      { name: 'Standard', price: 13500, description: '3-4 bed property EICR', includes: ['Full inspection', 'EICR certificate', 'Written report', 'Remedial quotes'] },
      { name: 'Premium', price: 19900, description: 'HMO / commercial EICR', includes: ['Full HMO inspection', 'EICR certificate', 'Written report', 'Remedial quotes', 'Landlord portal access'] },
    ],
    lat: 53.4800,
    lng: -2.2350,
  },
  {
    id: '4',
    slug: 'garden-maintenance-monthly',
    title: 'Monthly Garden Maintenance',
    subtitle: 'Professional garden upkeep on a recurring contract.',
    category: 'Gardening',
    providerName: 'Green Thumb Gardens',
    providerSlug: 'green-thumb-gardens',
    providerAvatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop&crop=face',
    providerPro: false,
    rating: 4.6,
    reviewCount: 67,
    jobsDone: 140,
    location: 'South Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    gallery: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800'],
    basePrice: 4500,
    standardPrice: 7500,
    premiumPrice: 12000,
    duration: '2-4 hours',
    responseTime: '< 1 week',
    nextAvailable: 'Sat 9:00 AM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Lawn mowing', 'Hedge trimming', 'Weed removal', 'Tidying & disposal'],
    tags: ['Residential', 'Flats & Houses'],
    packages: [
      { name: 'Basic', price: 4500, description: 'Small garden essentials', includes: ['Lawn mow', 'Edge trim', 'Weed check'] },
      { name: 'Standard', price: 7500, description: 'Medium garden monthly', includes: ['Lawn mow', 'Hedge trim', 'Weed removal', 'Tidy & dispose'] },
      { name: 'Premium', price: 12000, description: 'Full garden management', includes: ['Lawn mow', 'Hedge trim', 'Weed removal', 'Planting', 'Seasonal care'] },
    ],
    lat: 53.4300,
    lng: -2.2400,
  },
  {
    id: '5',
    slug: 'waste-clearance-full-house',
    title: 'Full House Clearance',
    subtitle: 'Complete property clearance, responsibly disposed.',
    category: 'Waste Removal',
    providerName: 'Northern Waste Management',
    providerSlug: 'northern-waste-management',
    providerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    providerPro: false,
    rating: 4.6,
    reviewCount: 89,
    jobsDone: 320,
    location: 'Salford',
    city: 'Salford',
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    gallery: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800'],
    basePrice: 15000,
    standardPrice: 25000,
    premiumPrice: 40000,
    duration: 'Full day',
    responseTime: '< 24 hours',
    nextAvailable: 'Mon 8:00 AM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['All items removed', 'Eco-friendly disposal', 'Duty of care certificate', 'Before & after photos'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    packages: [
      { name: 'Basic', price: 15000, description: '1-2 rooms or single items', includes: ['Collection', 'Eco disposal', 'Duty of care cert'] },
      { name: 'Standard', price: 25000, description: 'Full 1-2 bed property', includes: ['Full clearance', 'Eco disposal', 'Certificate', 'Photos'] },
      { name: 'Premium', price: 40000, description: '3+ bed or commercial', includes: ['Full clearance', 'Eco disposal', 'Certificate', 'Photos', 'Post-clearance clean'] },
    ],
    lat: 53.4900,
    lng: -2.2979,
  },
  {
    id: '6',
    slug: 'handyman-general-repairs',
    title: 'Handyman — General Repairs & Fixes',
    subtitle: 'Local handyman for small jobs & general maintenance.',
    category: 'Handyman',
    providerName: 'Premier Property Maintenance',
    providerSlug: 'premier-property-maintenance',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face',
    providerPro: false,
    rating: 4.5,
    reviewCount: 54,
    jobsDone: 180,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800',
    gallery: ['https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800'],
    basePrice: 5500,
    standardPrice: 8500,
    premiumPrice: 13500,
    duration: '2-6 hours',
    responseTime: '< 4 hours',
    nextAvailable: 'Today 5:00 PM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Any small repairs', 'Furniture assembly', 'Picture hanging', 'Shelving installation'],
    tags: ['Residential', 'Flats & Houses'],
    packages: [
      { name: 'Basic', price: 5500, description: 'Up to 2 hours of work', includes: ['Up to 2 small jobs', 'Labour only', 'Parts extra'] },
      { name: 'Standard', price: 8500, description: 'Half-day handyman', includes: ['Up to 4 hours', 'Multiple tasks', 'Basic materials included'] },
      { name: 'Premium', price: 13500, description: 'Full-day handyman', includes: ['Full day', 'Multiple tasks', 'Materials included', 'Priority booking'] },
    ],
    lat: 53.4820,
    lng: -2.2380,
  },
  {
    id: '7',
    slug: 'plumbing-bathroom-installation',
    title: 'Full Bathroom Installation',
    subtitle: 'Complete bathroom fit-out by certified plumbers.',
    category: 'Plumbing',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.8,
    reviewCount: 76,
    jobsDone: 230,
    location: 'Greater Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
    gallery: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800'],
    basePrice: 250000,
    standardPrice: 350000,
    premiumPrice: 500000,
    duration: '3-5 days',
    responseTime: '< 48 hours',
    nextAvailable: 'Next week',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Remove old bathroom', 'Install new suite', 'Tiling', 'Plumbing & waste', 'Final inspection'],
    tags: ['Residential', 'Commercial', 'HMO'],
    packages: [
      { name: 'Basic', price: 250000, description: 'Simple re-suite with supply-only', includes: ['Remove old suite', 'Install new suite', 'Basic plumbing'] },
      { name: 'Standard', price: 350000, description: 'Full fit with tiling', includes: ['Remove old suite', 'New suite', 'Tiling', 'Plumbing & waste'] },
      { name: 'Premium', price: 500000, description: 'Luxury full refit', includes: ['Full strip-out', 'Premium suite', 'Full tiling', 'Underfloor heating', 'Inspection cert'] },
    ],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: '8',
    slug: 'deep-carpet-cleaning',
    title: 'Professional Carpet Cleaning',
    subtitle: 'Hot water extraction for spotless carpets.',
    category: 'Cleaning',
    providerName: 'Bright Cleaning Services',
    providerSlug: 'bright-cleaning-services',
    providerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.7,
    reviewCount: 145,
    jobsDone: 560,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    gallery: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800'],
    basePrice: 6000,
    standardPrice: 9500,
    premiumPrice: 14500,
    duration: '2-5 hours',
    responseTime: '< 2 hours',
    nextAvailable: 'Today 3:00 PM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Pre-treatment', 'Hot water extraction', 'Stain removal', 'Fast dry'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    packages: [
      { name: 'Basic', price: 6000, description: 'Up to 2 rooms', includes: ['Pre-treatment', 'Hot water extraction', 'Fast dry'] },
      { name: 'Standard', price: 9500, description: 'Up to 5 rooms', includes: ['Pre-treatment', 'Hot water extraction', 'Stain removal', 'Fast dry'] },
      { name: 'Premium', price: 14500, description: 'Whole property including stairs', includes: ['Pre-treatment', 'Hot water extraction', 'Stain removal', 'Stairs', 'Deodoriser'] },
    ],
    lat: 53.4750,
    lng: -2.2500,
  },
  {
    id: '9',
    slug: 'gas-safety-certificate-landlord',
    title: 'Gas Safety Certificate (CP12)',
    subtitle: 'Mandatory annual gas safety inspection for landlords.',
    category: 'Heating',
    providerName: 'Ace Gas & Heating Services',
    providerSlug: 'ace-gas-heating-services',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.9,
    reviewCount: 189,
    jobsDone: 720,
    location: 'West Yorkshire',
    city: 'Leeds',
    heroImage: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800',
    gallery: ['https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800'],
    basePrice: 6500,
    standardPrice: 9500,
    premiumPrice: 15000,
    duration: '1-2 hours',
    responseTime: '< 48 hours',
    nextAvailable: 'Tomorrow 10:00 AM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Gas appliance check', 'Flue test', 'Safety inspection', 'CP12 certificate issued'],
    tags: ['Residential', 'Landlords', 'HMO'],
    packages: [
      { name: 'Basic', price: 6500, description: 'Single appliance (boiler only)', includes: ['Boiler inspection', 'Flue test', 'CP12 certificate'] },
      { name: 'Standard', price: 9500, description: 'Up to 3 appliances', includes: ['All appliance checks', 'Flue tests', 'CP12 certificate', 'Report'] },
      { name: 'Premium', price: 15000, description: 'HMO multi-appliance visit', includes: ['All appliances', 'Full safety check', 'CP12 certificate', 'Digital landlord copy', 'Reminder service'] },
    ],
    lat: 53.8008,
    lng: -1.5491,
  },
  {
    id: '10',
    slug: 'interior-painting-redecoration',
    title: 'Interior Painting & Redecoration',
    subtitle: 'Transform your rental property before new tenants move in.',
    category: 'Painting',
    providerName: 'Precision Painting & Decorating',
    providerSlug: 'precision-painting-decorating',
    providerAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.8,
    reviewCount: 167,
    jobsDone: 380,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800',
    gallery: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800'],
    basePrice: 35000,
    standardPrice: 55000,
    premiumPrice: 85000,
    duration: '2-5 days',
    responseTime: '< 24 hours',
    nextAvailable: 'Mon 8:00 AM',
    featured: true,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Surface prep', 'Primer coat', 'Top coat(s)', 'Clean up'],
    tags: ['Residential', 'Landlords', 'Flats & Houses'],
    packages: [
      { name: 'Basic', price: 35000, description: 'Studio or 1-bed flat', includes: ['Surface prep', 'Walls & ceilings 1 coat', 'Clean up'] },
      { name: 'Standard', price: 55000, description: '2-3 bed property', includes: ['Surface prep', 'Walls & ceilings 2 coats', 'Woodwork painted', 'Clean up'] },
      { name: 'Premium', price: 85000, description: '4+ bed or full redecoration', includes: ['Full prep', 'Walls & ceilings 2 coats', 'Woodwork & doors', 'Feature wall', 'Clean up'] },
    ],
    lat: 53.4750,
    lng: -2.2600,
  },
  {
    id: '11',
    slug: 'roof-repair-inspection',
    title: 'Roof Repair & Inspection',
    subtitle: 'Prevent leaks and storm damage with a professional roof check.',
    category: 'Roofing',
    providerName: 'Northern Roofing Specialists',
    providerSlug: 'northern-roofing-specialists',
    providerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.6,
    reviewCount: 95,
    jobsDone: 340,
    location: 'Greater Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1593620659530-8614a3474f2d?w=800',
    gallery: ['https://images.unsplash.com/photo-1593620659530-8614a3474f2d?w=800'],
    basePrice: 12000,
    standardPrice: 22000,
    premiumPrice: 45000,
    duration: '2-8 hours',
    responseTime: '4 hours',
    nextAvailable: 'Tomorrow',
    featured: false,
    verified: true,
    insured: true,
    urgent: true,
    deliverables: ['Roof inspection', 'Defect report', 'Repair of identified issues', 'Photo evidence'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    packages: [
      { name: 'Basic', price: 12000, description: 'Inspection only with report', includes: ['Visual inspection', 'Defect report', 'Photo evidence'] },
      { name: 'Standard', price: 22000, description: 'Inspection + minor repairs', includes: ['Full inspection', 'Report', 'Minor tile/flashing repairs'] },
      { name: 'Premium', price: 45000, description: 'Full repair with guarantee', includes: ['Full inspection', 'All repairs', 'New felt/flashing if needed', '5-year workmanship guarantee'] },
    ],
    lat: 53.5200,
    lng: -2.2100,
  },
  {
    id: '12',
    slug: 'cctv-security-installation',
    title: 'CCTV & Security System Installation',
    subtitle: 'Protect your rental property with smart CCTV.',
    category: 'Security',
    providerName: 'Swift Security Solutions',
    providerSlug: 'swift-security-solutions',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    providerPro: false,
    rating: 4.6,
    reviewCount: 74,
    jobsDone: 210,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    gallery: ['https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800'],
    basePrice: 35000,
    standardPrice: 65000,
    premiumPrice: 120000,
    duration: '1-2 days',
    responseTime: '< 48 hours',
    nextAvailable: 'This week',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Site survey', 'Camera installation', 'App setup', 'Handover training'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    packages: [
      { name: 'Basic', price: 35000, description: '2-camera starter kit', includes: ['2 HD cameras', 'Basic recorder', 'App setup'] },
      { name: 'Standard', price: 65000, description: '4-camera with cloud storage', includes: ['4 HD cameras', 'Cloud storage', 'App + alerts', 'Professional install'] },
      { name: 'Premium', price: 120000, description: 'Full property system', includes: ['8 cameras', 'NVR + cloud', 'Smart alerts', 'Access control', 'Annual support'] },
    ],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: '13',
    slug: 'hmo-property-inspection',
    title: 'HMO Property Inspection & Compliance',
    subtitle: 'Ensure your HMO meets all licensing and safety requirements.',
    category: 'Property Management',
    providerName: 'Metro Property Management',
    providerSlug: 'metro-property-management',
    providerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.7,
    reviewCount: 234,
    jobsDone: 640,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    gallery: ['https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800'],
    basePrice: 15000,
    standardPrice: 28000,
    premiumPrice: 50000,
    duration: '2-4 hours',
    responseTime: '< 48 hours',
    nextAvailable: 'This week',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Full HMO inspection', 'Compliance report', 'Licence check', 'Action plan'],
    tags: ['Residential', 'Landlords', 'HMO'],
    packages: [
      { name: 'Basic', price: 15000, description: 'Visual inspection only', includes: ['Visual check', 'Basic compliance report'] },
      { name: 'Standard', price: 28000, description: 'Full inspection + report', includes: ['Full inspection', 'Compliance report', 'Licence check', 'Action plan'] },
      { name: 'Premium', price: 50000, description: 'Inspection + follow-through', includes: ['Full inspection', 'Compliance report', 'Action plan', 'Follow-up visit', 'Council liaison'] },
    ],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: '14',
    slug: 'landlord-boiler-service',
    title: 'Annual Boiler Service',
    subtitle: 'Keep your boiler efficient and warranty-valid with a professional service.',
    category: 'Heating',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.8,
    reviewCount: 256,
    jobsDone: 1200,
    location: 'Greater Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800',
    gallery: ['https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800'],
    basePrice: 7500,
    standardPrice: 12000,
    premiumPrice: 18500,
    duration: '1-2 hours',
    responseTime: '< 48 hours',
    nextAvailable: 'Tomorrow',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Boiler service', 'Safety check', 'Filter clean', 'Service report'],
    tags: ['Residential', 'Landlords', 'HMO'],
    packages: [
      { name: 'Basic', price: 7500, description: 'Standard boiler service', includes: ['Annual service', 'Safety check', 'Service report'] },
      { name: 'Standard', price: 12000, description: 'Service + priority cover', includes: ['Service', 'Safety check', 'Filter clean', 'Priority cover 30 days'] },
      { name: 'Premium', price: 18500, description: 'Service + annual cover', includes: ['Full service', 'Safety check', 'Filter clean', '12-month cover', 'Free callout'] },
    ],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: '15',
    slug: 'damp-proofing-treatment',
    title: 'Damp Proofing & Mould Treatment',
    subtitle: 'Identify and fix damp issues before they damage your property.',
    category: 'Building',
    providerName: 'Heritage Property Preservation',
    providerSlug: 'heritage-property-preservation',
    providerAvatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.7,
    reviewCount: 156,
    jobsDone: 430,
    location: 'Stockport',
    city: 'Stockport',
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    gallery: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800'],
    basePrice: 20000,
    standardPrice: 40000,
    premiumPrice: 75000,
    duration: '1-3 days',
    responseTime: '< 24 hours',
    nextAvailable: 'This week',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Damp survey', 'Written report', 'Treatment', '10-year guarantee'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    packages: [
      { name: 'Basic', price: 20000, description: 'Damp survey and report only', includes: ['Damp survey', 'Written report', 'Recommendations'] },
      { name: 'Standard', price: 40000, description: 'Survey + mould treatment', includes: ['Survey', 'Mould treatment', 'Ventilation check', 'Report'] },
      { name: 'Premium', price: 75000, description: 'Full damp proofing with guarantee', includes: ['Full survey', 'Damp proof injection', 'Plaster repair', 'Mould treatment', '10-year guarantee'] },
    ],
    lat: 53.4059,
    lng: -2.1575,
  },
  {
    id: '16',
    slug: 'window-cleaning-portfolio',
    title: 'Commercial Window Cleaning',
    subtitle: 'Regular window cleaning contracts for landlords with multiple properties.',
    category: 'Cleaning',
    providerName: 'Bright Cleaning Services',
    providerSlug: 'bright-cleaning-services',
    providerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    providerPro: true,
    rating: 4.8,
    reviewCount: 89,
    jobsDone: 3400,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    gallery: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800'],
    basePrice: 2500,
    standardPrice: 4500,
    premiumPrice: 9500,
    duration: '1-3 hours',
    responseTime: '< 24 hours',
    nextAvailable: 'Tomorrow',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['All exterior windows', 'Frames wiped', 'Sills cleaned'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    packages: [
      { name: 'Basic', price: 2500, description: 'Up to 10 windows', includes: ['Exterior glass', 'Frame wipe', 'Sill clean'] },
      { name: 'Standard', price: 4500, description: 'Up to 25 windows', includes: ['Exterior glass', 'Frame wipe', 'Sill clean', 'Conservatory'] },
      { name: 'Premium', price: 9500, description: 'Portfolio contract (3+ properties)', includes: ['All windows', 'Frames', 'Sills', 'Gutters checked', 'Monthly schedule'] },
    ],
    lat: 53.4750,
    lng: -2.2500,
  },
]

export const SEED_EMERGENCY_SERVICES: PublicEmergencyService[] = [
  {
    id: '1',
    slug: 'emergency-locksmith-call-out',
    title: 'Emergency Locksmith Call-out',
    subtitle: 'Lockouts, broken locks & urgent entry · 24/7',
    category: 'Locksmith',
    providerName: 'Citywide Locksmiths',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'James Wilson',
    leadTechnicianRole: 'Lead Locksmith',
    phone: '0161 123 4567',
    rating: 4.9,
    reviewCount: 238,
    responseTimeMin: 20,
    responseTimeMax: 30,
    heroImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'M20'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£5M',
    baseCalloutPrice: 8500,
    noCalloutFee: true,
    description: 'Professional emergency locksmith service covering Greater Manchester 24/7.',
    coverageLat: 53.4808,
    coverageLng: -2.2426,
    priceItems: [
      { service: 'Standard lock open', from: 8500, to: 12000 },
      { service: 'Lock replacement', from: 12000, to: 18000 },
    ],
  },
  {
    id: '2',
    slug: 'emergency-plumbing-leak',
    title: 'Emergency Plumbing — Leak & Burst Pipe',
    subtitle: 'Immediate response to leaks, floods & burst pipes · 24/7',
    category: 'Plumbing',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'Mike Patel',
    leadTechnicianRole: 'Senior Plumber',
    phone: '0161 234 5678',
    rating: 4.8,
    reviewCount: 186,
    responseTimeMin: 25,
    responseTimeMax: 45,
    heroImage: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'M14', 'M15'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£5M',
    baseCalloutPrice: 9500,
    noCalloutFee: false,
    description: 'Emergency plumbing specialists available 24/7 for leaks, burst pipes and flooding.',
    coverageLat: 53.4808,
    coverageLng: -2.2426,
    priceItems: [
      { service: 'Emergency call-out', from: 9500 },
      { service: 'Burst pipe repair', from: 15000, to: 30000 },
    ],
  },
  {
    id: '3',
    slug: 'emergency-electrician',
    title: 'Emergency Electrician',
    subtitle: 'Power cuts, fuse faults & dangerous wiring · 24/7',
    category: 'Electrical',
    providerName: 'Manchester Electrical Solutions',
    providerSlug: 'manchester-electrical',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'Sarah Chen',
    leadTechnicianRole: 'Senior Electrician',
    phone: '0161 345 6789',
    rating: 4.9,
    reviewCount: 142,
    responseTimeMin: 30,
    responseTimeMax: 60,
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'M16'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£2M',
    baseCalloutPrice: 10000,
    noCalloutFee: false,
    coverageLat: 53.4800,
    coverageLng: -2.2350,
    priceItems: [
      { service: 'Emergency call-out', from: 10000 },
      { service: 'Electrical repair', from: 12000, to: 35000 },
    ],
  },
  {
    id: '4',
    slug: 'emergency-boarding-up',
    title: 'Emergency Boarding Up',
    subtitle: 'Broken windows, forced entry & vandalism secured fast',
    category: 'Security',
    providerName: 'Secure It Fast',
    providerSlug: 'premier-property-maintenance',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'Tom Hughes',
    leadTechnicianRole: 'Site Manager',
    phone: '0161 456 7890',
    rating: 4.7,
    reviewCount: 89,
    responseTimeMin: 30,
    responseTimeMax: 60,
    heroImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£2M',
    baseCalloutPrice: 7500,
    noCalloutFee: true,
    coverageLat: 53.4820,
    coverageLng: -2.2380,
    priceItems: [
      { service: 'Standard window boarding', from: 7500 },
      { service: 'Door boarding', from: 9500 },
    ],
  },
  {
    id: '5',
    slug: 'emergency-gas-engineer',
    title: 'Emergency Gas Engineer',
    subtitle: 'Gas leaks, unsafe appliances & carbon monoxide · 24/7',
    category: 'Gas',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'James Wilson',
    leadTechnicianRole: 'Gas Safe Engineer',
    phone: '0161 567 8901',
    rating: 4.9,
    reviewCount: 167,
    responseTimeMin: 20,
    responseTimeMax: 35,
    heroImage: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'M14', 'M15', 'M20'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£5M',
    baseCalloutPrice: 9500,
    noCalloutFee: false,
    coverageLat: 53.4808,
    coverageLng: -2.2426,
    priceItems: [
      { service: 'Emergency call-out', from: 9500 },
      { service: 'Gas leak detection & repair', from: 15000 },
    ],
  },
  {
    id: '6',
    slug: 'emergency-drain-unblocking',
    title: 'Emergency Drain Unblocking',
    subtitle: 'Blocked drains, toilets & sewers cleared fast · 24/7',
    category: 'Drainage',
    providerName: 'Clear Drains MCR',
    providerSlug: 'northern-waste-management',
    providerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'Paul Nash',
    leadTechnicianRole: 'Drainage Specialist',
    phone: '0161 678 9012',
    rating: 4.7,
    reviewCount: 123,
    responseTimeMin: 25,
    responseTimeMax: 50,
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6'],
    available24h: true,
    policeVetted: false,
    insured: true,
    insuranceAmount: '£1M',
    baseCalloutPrice: 8000,
    noCalloutFee: true,
    coverageLat: 53.4900,
    coverageLng: -2.2979,
    priceItems: [
      { service: 'Drain unblocking', from: 8000, to: 15000 },
      { service: 'CCTV drain survey', from: 15000 },
    ],
  },
  {
    id: '7',
    slug: 'emergency-roof-repair',
    title: 'Emergency Roof Repair',
    subtitle: 'Storm damage, leaks & fallen tiles fixed fast · 24/7',
    category: 'Roofing',
    providerName: 'Northern Roofing Specialists',
    providerSlug: 'northern-roofing-specialists',
    providerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'Dave Clark',
    leadTechnicianRole: 'Lead Roofer',
    phone: '0161 789 0123',
    rating: 4.6,
    reviewCount: 78,
    responseTimeMin: 45,
    responseTimeMax: 90,
    heroImage: 'https://images.unsplash.com/photo-1593620659530-8614a3474f2d?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'BL', 'WN'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£3M',
    baseCalloutPrice: 9500,
    noCalloutFee: false,
    description: 'Emergency roofing specialists covering Greater Manchester and surrounding areas.',
    coverageLat: 53.5200,
    coverageLng: -2.2100,
    priceItems: [
      { service: 'Emergency temporary repair', from: 9500 },
      { service: 'Tile replacement', from: 12000 },
    ],
  },
  {
    id: '8',
    slug: 'emergency-pest-control',
    title: 'Emergency Pest Control',
    subtitle: 'Rats, wasps, cockroaches & infestations removed fast · 24/7',
    category: 'Pest Control',
    providerName: 'Rapid Pest Solutions',
    providerSlug: 'premier-property-maintenance',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face',
    leadTechnicianName: 'Kevin Marsh',
    leadTechnicianRole: 'Pest Control Technician',
    phone: '0161 890 1234',
    rating: 4.8,
    reviewCount: 112,
    responseTimeMin: 30,
    responseTimeMax: 75,
    heroImage: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M5', 'M8', 'M14'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£1M',
    baseCalloutPrice: 7500,
    noCalloutFee: false,
    description: 'BPCA-certified pest control technicians for residential and commercial properties across Greater Manchester.',
    coverageLat: 53.4820,
    coverageLng: -2.2380,
    priceItems: [
      { service: 'Wasp nest treatment', from: 7500 },
      { service: 'Rat control (2 visits)', from: 12000 },
    ],
  },
]


export const SEED_LONG_TERM_RENTALS: PublicLongTermRental[] = [
  {
    id: 'ltr-1',
    slug: 'modern-2-bed-apartment-manchester',
    title: 'Modern 2-Bed Apartment, Ancoats',
    propertyType: 'Flat',
    location: 'Ancoats, Manchester M4',
    city: 'Manchester',
    postcode: 'M4 7EG',
    lat: 53.4841,
    lng: -2.2215,
    beds: 2,
    bathrooms: 1,
    maxOccupants: 4,
    furnishingStatus: 'Furnished',
    billsIncluded: false,
    petsAllowed: false,
    parkingAvailable: false,
    gardenAvailable: false,
    studentFriendly: false,
    familyFriendly: false,
    professionalFriendly: true,
    monthlyRentPence: 130000,
    depositPence: 150000,
    holdingDepositPence: 32500,
    councilTaxBand: 'C',
    epcRating: 'B',
    licenceVerified: true,
    landlordVerified: true,
    agentVerified: false,
    depositProtectionScheme: 'DPS',
    availableFrom: '2026-07-01',
    minTenancyMonths: 12,
    maxTenancyMonths: 24,
    rating: 4.8,
    reviewCount: 34,
    hostName: 'Ancoats Lettings',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    hostProBadge: true,
    heroImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    amenities: ['Fast Wi-Fi', 'Smart TV', 'Fully equipped kitchen', 'Washer/dryer', 'Intercom entry', 'Juliet balcony'],
    badges: ['professional-friendly', 'epc-b'],
    description: 'A stylish 2-bedroom apartment in the heart of Ancoats, Manchester\'s most sought-after neighbourhood. Open-plan living, floor-to-ceiling windows and premium finishes throughout. Walking distance to NOMA, Piccadilly and the best restaurants in the city.',
    features: ['Open-plan kitchen/living', 'Floor-to-ceiling windows', 'Built-in wardrobes', 'Underfloor heating', 'Video entry system'],
    nearbyTransport: ['Piccadilly Gardens (10 min walk)', 'Ancoats Metrolink (5 min walk)', 'Manchester Victoria (15 min walk)'],
    nearbyAmenities: ['Rudy\'s Pizza', 'Common Bar', 'Tesco Express', 'Ancoats Dispensary', 'Morrisons (7 min)'],
    rooms: [
      { name: 'Master bedroom', description: 'King-size bed, built-in wardrobe, floor-to-ceiling window' },
      { name: 'Bedroom 2', description: 'Double bed, built-in wardrobe' },
      { name: 'Bathroom', description: 'Walk-in shower, heated towel rail' },
      { name: 'Living/kitchen', description: 'Open-plan, island breakfast bar, Juliet balcony' },
    ],
  },
  {
    id: 'ltr-2',
    slug: 'bright-1-bed-flat-leeds',
    title: 'Bright 1-Bed Flat, Leeds City Centre',
    propertyType: 'Flat',
    location: 'City Centre, Leeds LS1',
    city: 'Leeds',
    postcode: 'LS1 4AJ',
    lat: 53.7996,
    lng: -1.5491,
    beds: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishingStatus: 'Furnished',
    billsIncluded: true,
    petsAllowed: false,
    parkingAvailable: false,
    gardenAvailable: false,
    studentFriendly: true,
    familyFriendly: false,
    professionalFriendly: true,
    monthlyRentPence: 95000,
    depositPence: 110000,
    holdingDepositPence: 23750,
    councilTaxBand: 'B',
    epcRating: 'C',
    licenceVerified: true,
    landlordVerified: false,
    agentVerified: true,
    depositProtectionScheme: 'TDS',
    availableFrom: '2026-07-15',
    minTenancyMonths: 6,
    maxTenancyMonths: 18,
    rating: 4.6,
    reviewCount: 21,
    hostName: 'Leeds City Lets',
    hostAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop',
    hostProBadge: false,
    heroImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['Wi-Fi included', 'Bills included', 'Smart TV', 'Kitchen', 'Cycle storage'],
    badges: ['bills-included', 'agent-verified'],
    description: 'A bright, well-presented 1-bedroom flat moments from Leeds city centre. All bills included — perfect for young professionals or students looking for hassle-free city living.',
    features: ['All bills included', 'South-facing windows', 'Modern kitchen', 'Secure building'],
    nearbyTransport: ['Leeds Station (8 min walk)', 'City Bus links outside'],
    nearbyAmenities: ['Trinity Leeds (5 min)', 'Morrisons (3 min)', 'Harvey Nichols (10 min)'],
    rooms: [
      { name: 'Bedroom', description: 'Double bed, fitted wardrobe' },
      { name: 'Bathroom', description: 'Bath with overhead shower' },
      { name: 'Living/kitchen', description: 'Open-plan, south-facing' },
    ],
  },
  {
    id: 'ltr-3',
    slug: '3-bed-house-garden-birmingham',
    title: '3-Bed Semi-Detached House with Garden',
    propertyType: 'House',
    location: 'Moseley, Birmingham B13',
    city: 'Birmingham',
    postcode: 'B13 9RJ',
    lat: 52.4421,
    lng: -1.8733,
    beds: 3,
    bathrooms: 2,
    maxOccupants: 5,
    furnishingStatus: 'Part furnished',
    billsIncluded: false,
    petsAllowed: true,
    parkingAvailable: true,
    gardenAvailable: true,
    studentFriendly: false,
    familyFriendly: true,
    professionalFriendly: false,
    monthlyRentPence: 145000,
    depositPence: 168000,
    holdingDepositPence: 36250,
    councilTaxBand: 'D',
    epcRating: 'D',
    licenceVerified: false,
    landlordVerified: true,
    agentVerified: false,
    depositProtectionScheme: 'myDeposits',
    availableFrom: '2026-08-01',
    minTenancyMonths: 12,
    rating: 4.7,
    reviewCount: 18,
    hostName: 'Moseley Homes',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    hostProBadge: false,
    heroImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    ],
    amenities: ['Private garden', 'Driveway parking', 'Washer/dryer', 'Dishwasher', 'Gas central heating', 'Pets welcome'],
    badges: ['pet-friendly', 'family-friendly', 'parking'],
    description: 'A spacious 3-bedroom semi-detached house in the desirable Moseley neighbourhood, just 3 miles from Birmingham city centre. Private garden, driveway and excellent local schools nearby.',
    features: ['Private rear garden', 'Off-road parking for 2 cars', 'Gas central heating', 'Double glazing throughout', 'Loft storage'],
    nearbyTransport: ['Kings Heath bus routes', 'Moseley Village (5 min walk)'],
    nearbyAmenities: ['Moseley Village shops', 'Alcester Road schools', 'Prince of Wales pub', 'Tesco (8 min)'],
    rooms: [
      { name: 'Master bedroom', description: 'Double bed, fitted wardrobe, en-suite shower room' },
      { name: 'Bedroom 2', description: 'Double bed, fitted wardrobe' },
      { name: 'Bedroom 3', description: 'Single/study, overlooks garden' },
      { name: 'Family bathroom', description: 'Bath, separate shower, WC' },
      { name: 'Lounge', description: 'Bay window, feature fireplace' },
      { name: 'Kitchen/diner', description: 'Integrated appliances, garden access' },
    ],
  },
  {
    id: 'ltr-4',
    slug: 'city-centre-studio-london',
    title: 'City Centre Studio, Shoreditch',
    propertyType: 'Studio',
    location: 'Shoreditch, London E1',
    city: 'London',
    postcode: 'E1 6RF',
    lat: 51.5236,
    lng: -0.0710,
    beds: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishingStatus: 'Furnished',
    billsIncluded: false,
    petsAllowed: false,
    parkingAvailable: false,
    gardenAvailable: false,
    studentFriendly: false,
    familyFriendly: false,
    professionalFriendly: true,
    monthlyRentPence: 200000,
    depositPence: 230000,
    holdingDepositPence: 50000,
    councilTaxBand: 'B',
    epcRating: 'C',
    licenceVerified: true,
    landlordVerified: true,
    agentVerified: true,
    depositProtectionScheme: 'DPS',
    availableFrom: '2026-07-01',
    minTenancyMonths: 6,
    maxTenancyMonths: 12,
    rating: 4.5,
    reviewCount: 42,
    hostName: 'East London Lets',
    hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    hostProBadge: true,
    heroImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['Fast Wi-Fi', 'Kitchenette', 'Smart TV', 'Bike storage', 'Video entry'],
    badges: ['professional-friendly', 'all-verified'],
    description: 'A compact, well-designed studio in the heart of Shoreditch. Ideal for a single professional wanting to be close to the City, Tech City and all that East London has to offer.',
    features: ['Open-plan studio layout', 'Murphy bed/sofa configuration', 'Integrated kitchen appliances', 'Secure building'],
    nearbyTransport: ['Liverpool Street (12 min walk)', 'Shoreditch High Street (4 min walk)'],
    nearbyAmenities: ['Brick Lane (5 min)', 'Spitalfields Market (10 min)', 'Waitrose (8 min)'],
    rooms: [
      { name: 'Studio', description: 'Open-plan, double bed, kitchenette, smart TV' },
      { name: 'Shower room', description: 'Walk-in shower, WC, heated towel rail' },
    ],
  },
  {
    id: 'ltr-5',
    slug: 'professional-hmo-room-manchester',
    title: 'Professional HMO Room, Didsbury',
    propertyType: 'Room',
    location: 'Didsbury, Manchester M20',
    city: 'Manchester',
    postcode: 'M20 2EU',
    lat: 53.4126,
    lng: -2.2297,
    beds: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishingStatus: 'Furnished',
    billsIncluded: true,
    petsAllowed: false,
    parkingAvailable: false,
    gardenAvailable: true,
    studentFriendly: false,
    familyFriendly: false,
    professionalFriendly: true,
    monthlyRentPence: 75000,
    depositPence: 75000,
    holdingDepositPence: 18750,
    councilTaxBand: 'C',
    epcRating: 'C',
    licenceVerified: true,
    landlordVerified: true,
    agentVerified: false,
    depositProtectionScheme: 'TDS',
    availableFrom: '2026-07-01',
    minTenancyMonths: 6,
    rating: 4.4,
    reviewCount: 67,
    hostName: 'Didsbury HMO Lets',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    hostProBadge: false,
    heroImage: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    amenities: ['Wi-Fi included', 'All bills included', 'Shared garden', 'Shared kitchen', 'Laundry room', 'Smart TV in room'],
    badges: ['bills-included', 'hmo-licensed'],
    description: 'A spacious double room in a licensed, professionally managed HMO in the leafy suburb of Didsbury. Shared with 4 other working professionals. All bills included.',
    features: ['All bills included', 'En-suite shower room', 'Double bed', 'Shared garden access', 'Secure cycle storage'],
    nearbyTransport: ['Didsbury Village tram (3 min walk)', 'Palatine Road bus'],
    nearbyAmenities: ['Didsbury Village (5 min)', 'M20 shops', 'The Didsbury pub'],
    rooms: [
      { name: 'Double room', description: 'Double bed, desk, built-in wardrobe, smart TV' },
      { name: 'En-suite', description: 'Walk-in shower, WC, basin' },
    ],
  },
  {
    id: 'ltr-6',
    slug: 'family-home-3-bed-london',
    title: 'Family Home — 3 Bedrooms, Walthamstow',
    propertyType: 'House',
    location: 'Walthamstow, London E17',
    city: 'London',
    postcode: 'E17 5QU',
    lat: 51.5848,
    lng: -0.0210,
    beds: 3,
    bathrooms: 2,
    maxOccupants: 5,
    furnishingStatus: 'Unfurnished',
    billsIncluded: false,
    petsAllowed: true,
    parkingAvailable: true,
    gardenAvailable: true,
    studentFriendly: false,
    familyFriendly: true,
    professionalFriendly: false,
    monthlyRentPence: 250000,
    depositPence: 288000,
    councilTaxBand: 'D',
    epcRating: 'D',
    licenceVerified: false,
    landlordVerified: true,
    agentVerified: true,
    depositProtectionScheme: 'myDeposits',
    availableFrom: '2026-08-01',
    minTenancyMonths: 12,
    rating: 4.9,
    reviewCount: 12,
    hostName: 'E17 Property Management',
    hostAvatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop',
    hostProBadge: false,
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    ],
    amenities: ['Private garden', 'Off-street parking', 'Gas central heating', 'Double glazing', 'Pets welcome', 'Large garden shed'],
    badges: ['family-friendly', 'pet-friendly', 'parking'],
    description: 'A well-maintained 3-bedroom Victorian terrace in Walthamstow, close to the tube and Walthamstow Village. Unfurnished with a large private garden — ideal for families.',
    features: ['Large private rear garden', 'Off-street parking for 1 car', 'Victorian period features', 'Two reception rooms', 'Utility room'],
    nearbyTransport: ['Walthamstow Central (Victoria/Overground) — 10 min walk', 'St James St (8 min walk)'],
    nearbyAmenities: ['Walthamstow Village', 'Lloyd Park', 'ASDA (5 min drive)', 'Outstanding primary schools nearby'],
    rooms: [
      { name: 'Master bedroom', description: 'Large double, front of house' },
      { name: 'Bedroom 2', description: 'Double, garden views' },
      { name: 'Bedroom 3', description: 'Single, currently used as home office' },
      { name: 'Family bathroom', description: 'Bath with shower over, heated towel rail' },
      { name: 'Shower room', description: 'Downstairs, WC and basin' },
    ],
  },
  {
    id: 'ltr-7',
    slug: 'student-studio-birmingham',
    title: 'Student Studio, Selly Oak',
    propertyType: 'Studio',
    location: 'Selly Oak, Birmingham B29',
    city: 'Birmingham',
    postcode: 'B29 6AT',
    lat: 52.4401,
    lng: -1.9319,
    beds: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishingStatus: 'Furnished',
    billsIncluded: true,
    petsAllowed: false,
    parkingAvailable: false,
    gardenAvailable: false,
    studentFriendly: true,
    familyFriendly: false,
    professionalFriendly: false,
    monthlyRentPence: 75000,
    depositPence: 75000,
    holdingDepositPence: 18750,
    councilTaxBand: 'A',
    epcRating: 'C',
    licenceVerified: true,
    landlordVerified: false,
    agentVerified: true,
    depositProtectionScheme: 'DPS',
    availableFrom: '2026-09-01',
    minTenancyMonths: 10,
    maxTenancyMonths: 12,
    rating: 4.3,
    reviewCount: 89,
    hostName: 'Selly Oak Student Lets',
    hostAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop',
    hostProBadge: true,
    heroImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    amenities: ['Wi-Fi included', 'All bills included', 'Smart TV', 'Kitchenette', 'Laundry on-site', 'Study desk'],
    badges: ['bills-included', 'student-friendly'],
    description: 'Affordable, fully-furnished studio in Selly Oak — Birmingham\'s student quarter. Steps from University of Birmingham campus. All bills included, academic year lets available.',
    features: ['All bills and Wi-Fi included', 'Study desk and chair', 'Kitchenette with microwave', 'Secure building with fob entry'],
    nearbyTransport: ['University of Birmingham (5 min walk)', 'Selly Oak train station (8 min walk)'],
    nearbyAmenities: ['Co-op (3 min)', 'Bournbrook High Street', 'Library and student union'],
    rooms: [
      { name: 'Studio', description: 'Double bed, study desk, wardrobe, smart TV, kitchenette' },
      { name: 'En-suite', description: 'Shower, WC, basin' },
    ],
  },
  {
    id: 'ltr-8',
    slug: '2-bed-terrace-leeds',
    title: '2-Bed Terraced House, Headingley',
    propertyType: 'House',
    location: 'Headingley, Leeds LS6',
    city: 'Leeds',
    postcode: 'LS6 1NZ',
    lat: 53.8267,
    lng: -1.5782,
    beds: 2,
    bathrooms: 1,
    maxOccupants: 4,
    furnishingStatus: 'Part furnished',
    billsIncluded: false,
    petsAllowed: true,
    parkingAvailable: false,
    gardenAvailable: true,
    studentFriendly: true,
    familyFriendly: true,
    professionalFriendly: true,
    monthlyRentPence: 112500,
    depositPence: 130000,
    holdingDepositPence: 28125,
    councilTaxBand: 'C',
    epcRating: 'E',
    licenceVerified: false,
    landlordVerified: true,
    agentVerified: false,
    depositProtectionScheme: 'TDS',
    availableFrom: '2026-07-01',
    minTenancyMonths: 6,
    rating: 4.5,
    reviewCount: 28,
    hostName: 'Headingley Homes',
    hostAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop',
    hostProBadge: false,
    heroImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    ],
    amenities: ['Private yard/garden', 'Gas central heating', 'Washer/dryer', 'Wi-Fi ready', 'Pets considered'],
    badges: ['pet-friendly'],
    description: 'A charming 2-bed terraced house in the heart of Headingley, Leeds. Close to the Otley Run, excellent pubs, cafes and Leeds University. Small private yard to the rear.',
    features: ['Private yard', 'Two reception rooms', 'Cellar storage', 'Gas heating'],
    nearbyTransport: ['Leeds city centre (15 min bus)', 'Headingley train station (10 min walk)'],
    nearbyAmenities: ['Headingley High Street', 'Hyde Park pub', 'Co-op (5 min walk)', 'Leeds Beckett University'],
    rooms: [
      { name: 'Bedroom 1', description: 'Double bed, front-facing' },
      { name: 'Bedroom 2', description: 'Double bed, rear garden views' },
      { name: 'Bathroom', description: 'Bath with shower, WC, basin' },
      { name: 'Lounge', description: 'Bay window, feature fireplace' },
      { name: 'Kitchen', description: 'Integrated oven/hob, rear yard access' },
    ],
  },
  {
    id: 'ltr-9',
    slug: 'luxury-penthouse-manchester',
    title: 'Luxury Penthouse, Deansgate Sq',
    propertyType: 'Penthouse',
    location: 'Deansgate Square, Manchester M15',
    city: 'Manchester',
    postcode: 'M15 4QN',
    lat: 53.4730,
    lng: -2.2500,
    beds: 3,
    bathrooms: 2,
    maxOccupants: 5,
    furnishingStatus: 'Furnished',
    billsIncluded: false,
    petsAllowed: false,
    parkingAvailable: true,
    gardenAvailable: false,
    studentFriendly: false,
    familyFriendly: false,
    professionalFriendly: true,
    monthlyRentPence: 320000,
    depositPence: 370000,
    holdingDepositPence: 80000,
    councilTaxBand: 'G',
    epcRating: 'B',
    licenceVerified: true,
    landlordVerified: true,
    agentVerified: true,
    depositProtectionScheme: 'DPS',
    availableFrom: '2026-08-01',
    minTenancyMonths: 12,
    rating: 5.0,
    reviewCount: 8,
    hostName: 'Deansgate Premium Lets',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    hostProBadge: true,
    heroImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
    ],
    amenities: ['Panoramic city views', 'Roof terrace access', 'Concierge', 'Gym & pool', 'Secure underground parking', 'Smart home system', 'Air conditioning'],
    badges: ['premium', 'all-verified', 'concierge'],
    description: 'An exceptional penthouse residence at Deansgate Square, offering breathtaking panoramic views across Manchester. 3 bedrooms, bespoke kitchen and a private roof terrace. Concierge, gym, pool and secure parking all included.',
    features: ['Panoramic views', 'Private roof terrace', 'Bespoke fitted kitchen', 'Smart home integration', 'Secure underground parking', 'Concierge 24/7'],
    nearbyTransport: ['Deansgate station (2 min walk)', 'St Peters Square (5 min walk)'],
    nearbyAmenities: ['Spinningfields (3 min)', 'Deansgate bars/restaurants', 'Harvey Nichols (5 min)', 'Waitrose (7 min)'],
    rooms: [
      { name: 'Master suite', description: 'Super-king, dressing room, en-suite bathroom with freestanding bath' },
      { name: 'Bedroom 2', description: 'King-size, panoramic views, en-suite shower' },
      { name: 'Bedroom 3', description: 'Double, city views, built-in wardrobe' },
      { name: 'Main bathroom', description: 'Family bathroom with bath and shower' },
      { name: 'Living/dining', description: 'Open-plan, floor-to-ceiling glazing, terrace access' },
    ],
  },
  {
    id: 'ltr-10',
    slug: 'garden-flat-london',
    title: 'Garden Flat — 2 Bedrooms, Clapham',
    propertyType: 'Flat',
    location: 'Clapham, London SW4',
    city: 'London',
    postcode: 'SW4 7UL',
    lat: 51.4629,
    lng: -0.1372,
    beds: 2,
    bathrooms: 1,
    maxOccupants: 3,
    furnishingStatus: 'Part furnished',
    billsIncluded: false,
    petsAllowed: true,
    parkingAvailable: false,
    gardenAvailable: true,
    studentFriendly: false,
    familyFriendly: true,
    professionalFriendly: true,
    monthlyRentPence: 265000,
    depositPence: 306000,
    holdingDepositPence: 66250,
    councilTaxBand: 'D',
    epcRating: 'D',
    licenceVerified: false,
    landlordVerified: true,
    agentVerified: false,
    depositProtectionScheme: 'myDeposits',
    availableFrom: '2026-07-20',
    minTenancyMonths: 12,
    rating: 4.7,
    reviewCount: 15,
    hostName: 'Clapham Property Co.',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    hostProBadge: false,
    heroImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    ],
    amenities: ['Private garden', 'Period features', 'Gas central heating', 'Washer/dryer', 'Separate utility room', 'Pets considered'],
    badges: ['pet-friendly', 'garden'],
    description: 'A beautiful garden flat on a tree-lined Victorian street in Clapham. Two bedrooms, a private garden and period features throughout. A rare find in one of London\'s most desirable neighbourhoods.',
    features: ['Private enclosed garden', 'Victorian period features', 'High ceilings', 'Original sash windows', 'Separate utility room'],
    nearbyTransport: ['Clapham Common (5 min walk)', 'Clapham North (8 min walk)'],
    nearbyAmenities: ['Clapham Common', 'Abbeville Road restaurants', 'Sainsbury\'s (5 min)', 'Clapham Leisure Centre'],
    rooms: [
      { name: 'Bedroom 1', description: 'Double bed, garden views, original fireplace' },
      { name: 'Bedroom 2', description: 'Double bed, built-in wardrobe' },
      { name: 'Bathroom', description: 'Roll-top bath, WC, basin' },
      { name: 'Reception', description: 'High ceilings, bay window, period fireplace' },
      { name: 'Kitchen', description: 'Fitted kitchen, garden access' },
    ],
  },
  {
    id: 'ltr-11',
    slug: 'townhouse-4-bed-birmingham',
    title: '4-Bed Townhouse, Jewellery Quarter',
    propertyType: 'Townhouse',
    location: 'Jewellery Quarter, Birmingham B18',
    city: 'Birmingham',
    postcode: 'B18 6NG',
    lat: 52.4879,
    lng: -1.9128,
    beds: 4,
    bathrooms: 3,
    maxOccupants: 6,
    furnishingStatus: 'Furnished',
    billsIncluded: false,
    petsAllowed: false,
    parkingAvailable: true,
    gardenAvailable: true,
    studentFriendly: false,
    familyFriendly: true,
    professionalFriendly: true,
    monthlyRentPence: 220000,
    depositPence: 255000,
    holdingDepositPence: 55000,
    councilTaxBand: 'E',
    epcRating: 'B',
    licenceVerified: true,
    landlordVerified: true,
    agentVerified: true,
    depositProtectionScheme: 'TDS',
    availableFrom: '2026-07-15',
    minTenancyMonths: 12,
    rating: 4.8,
    reviewCount: 22,
    hostName: 'JQ Property Partners',
    hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    hostProBadge: true,
    heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    amenities: ['Private roof terrace', 'Allocated parking', 'Smart home', 'Integrated appliances', 'Under-floor heating', 'Walled garden', 'EV charging point'],
    badges: ['premium', 'all-verified', 'ev-charging'],
    description: 'A stunning 4-bedroom contemporary townhouse in Birmingham\'s vibrant Jewellery Quarter. Three floors of stylish living space, a walled garden, roof terrace and allocated parking.',
    features: ['Three storeys of living', 'Walled garden', 'Roof terrace', 'Underfloor heating ground floor', 'EV charging point', 'Smart home automation'],
    nearbyTransport: ['Jewellery Quarter station (3 min walk)', 'New Street (15 min)'],
    nearbyAmenities: ['JQ restaurants & bars', 'Bodega Bar', 'Tesco Express (5 min)', 'HSBC UK Arena (20 min)'],
    rooms: [
      { name: 'Master suite', description: 'King-size, en-suite with freestanding bath and walk-in shower' },
      { name: 'Bedroom 2', description: 'Double bed, en-suite shower room' },
      { name: 'Bedroom 3', description: 'Double bed, built-in wardrobe' },
      { name: 'Bedroom 4', description: 'Double/home office, garden views' },
      { name: 'Family bathroom', description: 'Separate WC and shower' },
    ],
  },
  {
    id: 'ltr-12',
    slug: 'furnished-room-city-centre-leeds',
    title: 'Furnished Double Room, Leeds City Centre',
    propertyType: 'Room',
    location: 'City Centre, Leeds LS1',
    city: 'Leeds',
    postcode: 'LS1 5BJ',
    lat: 53.7980,
    lng: -1.5441,
    beds: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishingStatus: 'Furnished',
    billsIncluded: true,
    petsAllowed: false,
    parkingAvailable: false,
    gardenAvailable: false,
    studentFriendly: true,
    familyFriendly: false,
    professionalFriendly: true,
    monthlyRentPence: 82500,
    depositPence: 82500,
    holdingDepositPence: 20625,
    councilTaxBand: 'B',
    epcRating: 'C',
    licenceVerified: true,
    landlordVerified: false,
    agentVerified: true,
    depositProtectionScheme: 'DPS',
    availableFrom: '2026-07-01',
    minTenancyMonths: 6,
    rating: 4.5,
    reviewCount: 54,
    hostName: 'Leeds Central Rooms',
    hostAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop',
    hostProBadge: false,
    heroImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    amenities: ['Wi-Fi included', 'All bills included', 'Shared kitchen', 'Shared lounge', 'Laundry room', 'Smart TV in room'],
    badges: ['bills-included', 'city-centre'],
    description: 'A spacious furnished double room in a modern shared house right in Leeds city centre. All bills and fast Wi-Fi included. Housemates are a mix of working professionals and postgrads.',
    features: ['All bills and Wi-Fi included', 'Double bed with storage', 'Study desk and chair', 'Modern shared facilities'],
    nearbyTransport: ['Leeds Station (5 min walk)', 'City bus network outside'],
    nearbyAmenities: ['Trinity Leeds (3 min)', 'Kirkgate Market (5 min)', 'ASDA (7 min)'],
    rooms: [
      { name: 'Double room', description: 'Double bed, storage, desk, smart TV' },
      { name: 'Shared bathroom', description: 'Shared with 1 other housemate' },
    ],
  },
]