import type { PublicStay, PublicProvider, PublicServiceOffer, PublicEmergencyService } from './types'

// NOTE: Images use Unsplash CDN URLs for development/demo only.
// Replace with real CDN assets before production.

export const SEED_STAYS: PublicStay[] = [
  {
    id: '1',
    slug: 'luxury-2-bed-apartment-shoreditch',
    title: 'Luxury 2-Bed Apartment, Shoreditch',
    stayType: 'Entire home',
    location: 'Shoreditch, London E2',
    city: 'London',
    postcode: 'E2',
    beds: 2,
    bathrooms: 2,
    guests: 4,
    bedrooms: 2,
    rating: 4.9,
    reviewCount: 128,
    pricePerNight: 14500,
    cleaningFee: 4500,
    serviceFee: 2300,
    taxes: 1700,
    verified: true,
    instantBook: true,
    freeCancellation: true,
    shortLets: true,
    longStays: false,
    petsAllowed: false,
    hostName: 'Manchester Stays',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 128,
    hostRating: 4.9,
    hostReviews: 1248,
    hostResponseTime: '20 mins',
    heroImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    lat: 51.5239,
    lng: -0.0693,
    amenities: ['Fast Wi-Fi 175Mbps', 'Smart TV with Netflix', 'Fully equipped kitchen', 'Washer & dryer', 'Private balcony', 'Central heating'],
    badges: ['bills-included', 'fast-wifi', 'weekly-cleaning'],
    description: 'A beautifully designed 2-bedroom apartment in the heart of Shoreditch. This stunning space features exposed brick walls, high ceilings and premium finishes throughout. Perfect for professionals, couples or small families seeking a premium base in East London.',
    highlights: ['Entire home', 'Self check-in', 'Great location', 'Fast Wi-Fi'],
    houseRules: ['No smoking', 'No parties or events', 'Check-in: 3PM', 'Check-out: 11AM', 'Pets not allowed'],
    cancellationPolicy: 'Free cancellation before 48 hours. After that, 50% refund for cancellations made at least 7 days before check-in.',
    rooms: [
      { name: 'Bedroom 1', description: 'King-size bed, en-suite bathroom, built-in wardrobe' },
      { name: 'Bedroom 2', description: 'Queen-size bed, balcony access, built-in wardrobe' },
      { name: 'Living room', description: 'Sofa bed (sleeps 2), Smart TV, open plan' },
      { name: 'Bathrooms', description: '2 full bathrooms, rainfall shower, luxury toiletries' },
    ],
  },
  {
    id: '2',
    slug: 'modern-studio-spinningfields',
    title: 'Modern Studio, Spinningfields',
    stayType: 'Studio',
    location: 'Spinningfields, Manchester M3',
    city: 'Manchester',
    postcode: 'M3',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.7,
    reviewCount: 86,
    pricePerNight: 8500,
    cleaningFee: 2500,
    serviceFee: 1200,
    taxes: 900,
    verified: true,
    instantBook: true,
    freeCancellation: false,
    shortLets: true,
    longStays: false,
    petsAllowed: false,
    hostName: 'City Stays MCR',
    hostAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 45,
    hostRating: 4.7,
    hostReviews: 623,
    hostResponseTime: '15 mins',
    heroImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    lat: 53.4793,
    lng: -2.2529,
    amenities: ['Fast Wi-Fi', 'Smart TV', 'Kitchen', 'Gym access', 'Concierge'],
    badges: ['bills-included'],
    description: "Sleek studio apartment in the heart of Manchester's financial district. Walking distance to Deansgate, Salford Quays and top restaurants.",
    highlights: ['Self check-in', 'Great location', 'Fast Wi-Fi', 'Gym access'],
    rooms: [{ name: 'Studio', description: 'Open plan living, double bed, fully equipped kitchen' }],
  },
  {
    id: '3',
    slug: 'charming-cottage-didsbury',
    title: 'Charming 3-Bed Cottage, Didsbury',
    stayType: 'Entire home',
    location: 'Didsbury, Manchester M20',
    city: 'Manchester',
    postcode: 'M20',
    beds: 3,
    bathrooms: 2,
    guests: 6,
    bedrooms: 3,
    rating: 4.8,
    reviewCount: 203,
    pricePerNight: 12000,
    cleaningFee: 5500,
    serviceFee: 1800,
    taxes: 1400,
    verified: true,
    instantBook: false,
    freeCancellation: true,
    shortLets: false,
    longStays: true,
    petsAllowed: true,
    hostName: 'Didsbury Homes',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 8,
    hostRating: 4.8,
    hostReviews: 412,
    hostResponseTime: '1 hour',
    heroImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    lat: 53.4126,
    lng: -2.2297,
    amenities: ['Garden', 'Parking', 'Wi-Fi', 'Washer', 'Dishwasher', 'Pets welcome'],
    badges: ['pet-friendly', 'long-stay'],
    description: 'Beautiful Victorian cottage with a private garden in the leafy suburb of Didsbury. Perfect for families or groups looking for a longer stay.',
    rooms: [
      { name: 'Master bedroom', description: 'King bed, en-suite' },
      { name: 'Bedroom 2', description: 'Double bed' },
      { name: 'Bedroom 3', description: 'Twin beds' },
    ],
  },
  {
    id: '4',
    slug: 'city-centre-penthouse-northern-quarter',
    title: 'City Centre Penthouse, Northern Quarter',
    stayType: 'Penthouse',
    location: 'Northern Quarter, Manchester M4',
    city: 'Manchester',
    postcode: 'M4',
    beds: 2,
    bathrooms: 2,
    guests: 4,
    bedrooms: 2,
    rating: 5.0,
    reviewCount: 47,
    pricePerNight: 18000,
    cleaningFee: 6000,
    serviceFee: 2800,
    taxes: 2100,
    verified: true,
    instantBook: true,
    freeCancellation: true,
    shortLets: true,
    longStays: false,
    petsAllowed: false,
    hostName: 'Northern Quarter Stays',
    hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 23,
    hostRating: 5.0,
    hostReviews: 189,
    hostResponseTime: '10 mins',
    heroImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    lat: 53.4841,
    lng: -2.2354,
    amenities: ['Panoramic views', 'Roof terrace', 'Fast Wi-Fi', 'Smart home', 'Concierge'],
    badges: ['premium', 'new-listing'],
    description: 'Stunning penthouse apartment with panoramic views over Manchester city centre. Roof terrace perfect for entertaining.',
    rooms: [
      { name: 'Master suite', description: 'Super king bed, en-suite with freestanding bath' },
      { name: 'Bedroom 2', description: 'King bed, city views' },
    ],
  },
  {
    id: '5',
    slug: 'private-room-salford-quays',
    title: 'Private Room, Salford Quays',
    stayType: 'Private room',
    location: 'Salford Quays, Salford M50',
    city: 'Salford',
    postcode: 'M50',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.6,
    reviewCount: 134,
    pricePerNight: 4500,
    cleaningFee: 1500,
    serviceFee: 700,
    taxes: 500,
    verified: true,
    instantBook: true,
    freeCancellation: true,
    shortLets: true,
    longStays: true,
    petsAllowed: false,
    hostName: 'Quays Rentals',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 4,
    hostRating: 4.6,
    hostReviews: 267,
    hostResponseTime: '30 mins',
    heroImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    gallery: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'],
    lat: 53.4726,
    lng: -2.2979,
    amenities: ['Wi-Fi', 'Shared kitchen', 'MediaCity access', 'Parking'],
    badges: [],
    description: 'Bright private room with waterfront views near MediaCity UK. Great transport links into Manchester city centre.',
  },
  {
    id: '6',
    slug: 'luxury-1-bed-chorlton',
    title: 'Luxury 1-Bed Flat, Chorlton',
    stayType: 'Entire home',
    location: 'Chorlton, Manchester M21',
    city: 'Manchester',
    postcode: 'M21',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.8,
    reviewCount: 91,
    pricePerNight: 7800,
    cleaningFee: 2000,
    serviceFee: 1100,
    taxes: 800,
    verified: true,
    instantBook: false,
    freeCancellation: true,
    shortLets: true,
    longStays: true,
    petsAllowed: true,
    hostName: 'Chorlton Lets',
    hostAvatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 6,
    hostRating: 4.8,
    hostReviews: 341,
    hostResponseTime: '45 mins',
    heroImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    gallery: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800'],
    lat: 53.4407,
    lng: -2.2770,
    amenities: ['Garden', 'Wi-Fi', 'Washer', 'Pets OK', 'Quiet street'],
    badges: ['pet-friendly'],
  },
  {
    id: '7',
    slug: 'serviced-apartment-manchester-city',
    title: 'Serviced Apartment, Manchester City',
    stayType: 'Entire home',
    location: 'City Centre, Manchester M1',
    city: 'Manchester',
    postcode: 'M1',
    beds: 1,
    bathrooms: 1,
    guests: 2,
    bedrooms: 1,
    rating: 4.7,
    reviewCount: 312,
    pricePerNight: 9500,
    cleaningFee: 2500,
    serviceFee: 1400,
    taxes: 1000,
    verified: true,
    instantBook: true,
    freeCancellation: false,
    shortLets: true,
    longStays: true,
    petsAllowed: false,
    hostName: 'Manchester Stays',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    hostProBadge: true,
    hostProperties: 128,
    hostRating: 4.9,
    hostReviews: 1248,
    hostResponseTime: '20 mins',
    heroImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    gallery: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    lat: 53.4808,
    lng: -2.2426,
    amenities: ['Wi-Fi', 'Gym', 'Concierge', 'Smart TV', 'Housekeeping'],
    badges: ['bills-included', 'weekly-cleaning'],
  },
  {
    id: '8',
    slug: 'hmo-room-fallowfield',
    title: 'Furnished Room, Fallowfield',
    stayType: 'Private room',
    location: 'Fallowfield, Manchester M14',
    city: 'Manchester',
    postcode: 'M14',
    beds: 1,
    bathrooms: 1,
    guests: 1,
    bedrooms: 1,
    rating: 4.4,
    reviewCount: 67,
    pricePerNight: 3500,
    cleaningFee: 1000,
    serviceFee: 500,
    taxes: 400,
    verified: false,
    instantBook: true,
    freeCancellation: true,
    shortLets: false,
    longStays: true,
    petsAllowed: false,
    hostName: 'Student Stays MCR',
    hostAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop',
    hostProBadge: false,
    hostProperties: 12,
    hostRating: 4.4,
    hostReviews: 234,
    hostResponseTime: '2 hours',
    heroImage: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
    gallery: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800'],
    lat: 53.4440,
    lng: -2.2169,
    amenities: ['Wi-Fi', 'Bills included', 'Shared kitchen', 'Laundry'],
    badges: ['bills-included', 'long-stay'],
  },
]

export const SEED_PROVIDERS: PublicProvider[] = [
  {
    id: '1',
    slug: 'citywide-plumbing-heating',
    companyName: 'Citywide Plumbing & Heating',
    trade: 'Plumbing & Heating Services',
    location: 'Greater Manchester, UK',
    city: 'Manchester',
    rating: 4.8,
    reviewCount: 128,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£5M',
    teamSize: 48,
    jobsDone: 2450,
    yearsActive: 12,
    responseTime: '28 mins',
    fromPrice: 8500,
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    logo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    certifications: ['Gas Safe', 'NICEIC', 'DBS Verified', 'CHAS'],
    coverageRadius: 50,
    coverageCities: ['Manchester', 'Salford', 'Stockport', 'Bury', 'Oldham', 'Rochdale'],
    featured: true,
    emergency24h: true,
    gasSafe: '556789',
    description: "Greater Manchester's leading plumbing and heating specialists with over 12 years of experience serving residential and commercial properties.",
    services: ['Boiler installation', 'Boiler repair', 'Central heating', 'Emergency plumbing', 'Bathroom installation', 'Gas safety certificates'],
    faqs: [
      { q: 'Do you offer emergency call-outs?', a: 'Yes, we offer 24/7 emergency call-outs across Greater Manchester with a typical arrival time of 28 minutes.' },
      { q: 'Are you Gas Safe registered?', a: 'Yes, all our engineers are Gas Safe registered (No. 556789). We can provide certificates on request.' },
      { q: 'What areas do you cover?', a: 'We cover all of Greater Manchester within a 50-mile radius including Salford, Stockport, Bury, Oldham and Rochdale.' },
      { q: 'Do you provide upfront pricing?', a: 'Yes, we always provide a fixed price quote before starting any work. No hidden charges.' },
    ],
    recentWork: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400',
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
      'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400',
    ],
    teamMembers: [
      { name: 'James Wilson', role: 'Lead Engineer', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop' },
      { name: 'Sarah Chen', role: 'Senior Plumber', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop' },
      { name: 'Mike Patel', role: 'Gas Engineer', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop' },
      { name: 'Tom Hughes', role: 'Apprentice', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop' },
      { name: 'Lisa Park', role: 'Office Manager', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop' },
    ],
    lat: 53.4808,
    lng: -2.2426,
    initials: 'CPH',
    pinColor: '#2563eb',
  },
  {
    id: '2',
    slug: 'manchester-electrical',
    companyName: 'Manchester Electrical Solutions',
    trade: 'Electrical Services',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.9,
    reviewCount: 203,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£2M',
    teamSize: 22,
    jobsDone: 1820,
    yearsActive: 8,
    responseTime: '35 mins',
    fromPrice: 7500,
    heroImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800',
    logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    certifications: ['NICEIC', 'Part P', 'DBS Verified'],
    coverageRadius: 30,
    coverageCities: ['Manchester', 'Salford', 'Trafford', 'Tameside'],
    featured: true,
    emergency24h: true,
    niceic: true,
    description: 'NICEIC-approved electrical contractors serving residential and commercial clients across Greater Manchester.',
    lat: 53.4800,
    lng: -2.2350,
    initials: 'ME',
    pinColor: '#7c3aed',
  },
  {
    id: '3',
    slug: 'northern-waste-management',
    companyName: 'Northern Waste Management',
    trade: 'Waste Removal & Clearance',
    location: 'Salford, UK',
    city: 'Salford',
    rating: 4.6,
    reviewCount: 89,
    proBadge: false,
    vetted: true,
    insured: true,
    insuranceAmount: '£1M',
    teamSize: 12,
    jobsDone: 480,
    yearsActive: 6,
    responseTime: '30 mins',
    fromPrice: 6500,
    heroImage: 'https://images.unsplash.com/photo-1558618047-3c8c76ca6e5b?w=800',
    logo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    certifications: ['Waste Carrier Licence', 'DBS'],
    coverageRadius: 25,
    coverageCities: ['Salford', 'Manchester', 'Eccles', 'Worsley'],
    featured: false,
    emergency24h: false,
    lat: 53.4900,
    lng: -2.2979,
    initials: 'NW',
    pinColor: '#059669',
  },
  {
    id: '4',
    slug: 'heritage-property-preservation',
    companyName: 'Heritage Property Preservation',
    trade: 'Building & Restoration',
    location: 'Stockport, UK',
    city: 'Stockport',
    rating: 4.7,
    reviewCount: 156,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£10M',
    teamSize: 35,
    jobsDone: 890,
    yearsActive: 18,
    responseTime: '2 hours',
    fromPrice: 15000,
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
    logo: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop',
    certifications: ['NHBC', 'CHAS', 'ISO 9001'],
    coverageRadius: 40,
    coverageCities: ['Stockport', 'Manchester', 'Cheadle', 'Macclesfield'],
    featured: true,
    emergency24h: false,
    lat: 53.4059,
    lng: -2.1575,
    initials: 'HPP',
    pinColor: '#d97706',
  },
  {
    id: '5',
    slug: 'bright-cleaning-services',
    companyName: 'Bright Cleaning Services',
    trade: 'Professional Cleaning',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.8,
    reviewCount: 445,
    proBadge: true,
    vetted: true,
    insured: true,
    insuranceAmount: '£1M',
    teamSize: 64,
    jobsDone: 5200,
    yearsActive: 9,
    responseTime: '15 mins',
    fromPrice: 4500,
    heroImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    logo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    certifications: ['BICSc', 'DBS', 'ISO 14001'],
    coverageRadius: 20,
    coverageCities: ['Manchester', 'Salford', 'Trafford'],
    featured: false,
    emergency24h: false,
    lat: 53.4750,
    lng: -2.2500,
    initials: 'BCS',
    pinColor: '#0891b2',
  },
  {
    id: '6',
    slug: 'premier-property-maintenance',
    companyName: 'Premier Property Maintenance',
    trade: 'General Maintenance & Repairs',
    location: 'Manchester, UK',
    city: 'Manchester',
    rating: 4.5,
    reviewCount: 78,
    proBadge: false,
    vetted: true,
    insured: true,
    insuranceAmount: '£2M',
    teamSize: 8,
    jobsDone: 320,
    yearsActive: 4,
    responseTime: '45 mins',
    fromPrice: 5500,
    heroImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
    logo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop',
    certifications: ['DBS'],
    coverageRadius: 15,
    coverageCities: ['Manchester', 'Salford'],
    featured: false,
    emergency24h: false,
    lat: 53.4820,
    lng: -2.2380,
    initials: 'PPM',
    pinColor: '#dc2626',
  },
]

export const SEED_SERVICE_OFFERS: PublicServiceOffer[] = [
  {
    id: '1',
    slug: 'end-of-tenancy-deep-clean',
    title: 'End of Tenancy Deep Clean',
    subtitle: 'Move-out cleaning that gets your deposit back.',
    category: 'Cleaning',
    providerName: 'Sparkle Clean Services',
    providerSlug: 'bright-cleaning-services',
    providerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    providerPro: true,
    rating: 4.8,
    reviewCount: 128,
    jobsDone: 200,
    location: 'West Yorkshire',
    city: 'Leeds',
    heroImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
      'https://images.unsplash.com/photo-1558618047-f3f7af5780df?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    basePrice: 12000,
    standardPrice: 18000,
    premiumPrice: 26000,
    duration: '3-8 hours',
    responseTime: '< 2 hours',
    nextAvailable: 'Today 2:00 PM',
    featured: true,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Full kitchen deep clean', 'All bathrooms sanitised', 'Carpets vacuumed', 'Windows cleaned', 'Oven interior clean'],
    tags: ['Residential', 'Tenants & Landlords', 'Flats & Houses', 'Move-out Ready'],
    packages: [
      {
        name: 'Basic',
        price: 12000,
        description: 'Essential clean for 1-bed properties',
        includes: ['Kitchen surface clean', 'Bathroom clean', 'Living areas hoovered', 'Bedroom hoovered', 'Interior windows'],
      },
      {
        name: 'Standard',
        price: 18000,
        description: 'For 2-3 bed properties · Most popular',
        includes: ['Kitchen deep clean', 'Bathroom sanitisation', 'Living areas full clean', 'Bedrooms (up to 2)', 'Interior windows', 'Skirting boards', 'Oven clean included'],
      },
      {
        name: 'Premium',
        price: 26000,
        description: 'Deep & detailed for 3+ bed properties',
        includes: ['Full kitchen deep clean', 'All bathrooms deep clean', 'All living areas full clean', 'All bedrooms (up to 3)', 'All windows inside & out', 'Skirting boards & switches', 'Oven & fridge', 'Carpet shampooing'],
      },
    ],
    addons: [
      { name: 'Oven deep clean', price: 4000 },
      { name: 'Carpet shampoo', price: 6000 },
      { name: 'Fridge interior', price: 2000 },
      { name: 'Photo report', price: 1500 },
      { name: 'Same-day service', price: 3000 },
    ],
    lat: 53.8008,
    lng: -1.5491,
  },
  {
    id: '2',
    slug: 'emergency-boiler-repair',
    title: 'Emergency Boiler Repair',
    subtitle: 'Same-day boiler repairs by Gas Safe engineers.',
    category: 'Plumbing',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    providerPro: true,
    rating: 4.9,
    reviewCount: 312,
    jobsDone: 850,
    location: 'Greater Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    gallery: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
    basePrice: 8500,
    standardPrice: 12500,
    premiumPrice: 18500,
    duration: '1-3 hours',
    responseTime: '28 mins',
    nextAvailable: 'Now',
    featured: true,
    verified: true,
    insured: true,
    urgent: true,
    deliverables: ['Fault diagnosis', 'Part replacement (if needed)', 'Safety check', 'Gas Safe certificate'],
    tags: ['Residential', 'Commercial', 'Emergency'],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: '3',
    slug: 'electrical-safety-certificate',
    title: 'Electrical Safety Certificate (EICR)',
    subtitle: 'NICEIC-approved EICR for landlords & letting agents.',
    category: 'Electrical',
    providerName: 'Manchester Electrical Solutions',
    providerSlug: 'manchester-electrical',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    providerPro: true,
    rating: 4.9,
    reviewCount: 203,
    jobsDone: 680,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800',
    gallery: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800'],
    basePrice: 9900,
    standardPrice: 13500,
    premiumPrice: 19900,
    duration: '2-4 hours',
    responseTime: '< 24 hours',
    nextAvailable: 'Tomorrow 9:00 AM',
    featured: true,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Full EICR inspection', 'Written report', 'Certificate issued', 'Remedial quote if needed'],
    tags: ['Residential', 'Landlords', 'HMO'],
    lat: 53.4800,
    lng: -2.2350,
  },
  {
    id: '4',
    slug: 'garden-maintenance-monthly',
    title: 'Monthly Garden Maintenance',
    subtitle: 'Professional garden upkeep on a recurring contract.',
    category: 'Gardening',
    providerName: 'Green Thumb Gardens',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=80&h=80&fit=crop',
    providerPro: false,
    rating: 4.6,
    reviewCount: 67,
    jobsDone: 140,
    location: 'South Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    gallery: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800'],
    basePrice: 4500,
    standardPrice: 7500,
    premiumPrice: 12000,
    duration: '2-4 hours',
    responseTime: '< 1 week',
    nextAvailable: 'Sat 9:00 AM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Lawn mowing', 'Hedge trimming', 'Weed removal', 'Tidying & disposal'],
    tags: ['Residential', 'Flats & Houses'],
    lat: 53.4300,
    lng: -2.2400,
  },
  {
    id: '5',
    slug: 'waste-clearance-full-house',
    title: 'Full House Clearance',
    subtitle: 'Complete property clearance, responsibly disposed.',
    category: 'Waste Removal',
    providerName: 'Northern Waste Management',
    providerSlug: 'northern-waste-management',
    providerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    providerPro: false,
    rating: 4.6,
    reviewCount: 89,
    jobsDone: 320,
    location: 'Salford',
    city: 'Salford',
    heroImage: 'https://images.unsplash.com/photo-1558618047-3c8c76ca6e5b?w=800',
    gallery: ['https://images.unsplash.com/photo-1558618047-3c8c76ca6e5b?w=800'],
    basePrice: 15000,
    standardPrice: 25000,
    premiumPrice: 40000,
    duration: 'Full day',
    responseTime: '< 24 hours',
    nextAvailable: 'Mon 8:00 AM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['All items removed', 'Eco-friendly disposal', 'Duty of care certificate', 'Before & after photos'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    lat: 53.4900,
    lng: -2.2979,
  },
  {
    id: '6',
    slug: 'handyman-general-repairs',
    title: 'Handyman — General Repairs & Fixes',
    subtitle: 'Local handyman for small jobs & general maintenance.',
    category: 'Handyman',
    providerName: 'Premier Property Maintenance',
    providerSlug: 'premier-property-maintenance',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop',
    providerPro: false,
    rating: 4.5,
    reviewCount: 54,
    jobsDone: 180,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
    gallery: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800'],
    basePrice: 5500,
    standardPrice: 8500,
    premiumPrice: 13500,
    duration: '2-6 hours',
    responseTime: '< 4 hours',
    nextAvailable: 'Today 5:00 PM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Any small repairs', 'Furniture assembly', 'Picture hanging', 'Shelving installation'],
    tags: ['Residential', 'Flats & Houses'],
    lat: 53.4820,
    lng: -2.2380,
  },
  {
    id: '7',
    slug: 'plumbing-bathroom-installation',
    title: 'Full Bathroom Installation',
    subtitle: 'Complete bathroom fit-out by certified plumbers.',
    category: 'Plumbing',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    providerPro: true,
    rating: 4.8,
    reviewCount: 76,
    jobsDone: 230,
    location: 'Greater Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
    gallery: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800'],
    basePrice: 250000,
    standardPrice: 350000,
    premiumPrice: 500000,
    duration: '3-5 days',
    responseTime: '< 48 hours',
    nextAvailable: 'Next week',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Remove old bathroom', 'Install new suite', 'Tiling', 'Plumbing & waste', 'Final inspection'],
    tags: ['Residential', 'Commercial', 'HMO'],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: '8',
    slug: 'deep-carpet-cleaning',
    title: 'Professional Carpet Cleaning',
    subtitle: 'Hot water extraction for spotless carpets.',
    category: 'Cleaning',
    providerName: 'Bright Cleaning Services',
    providerSlug: 'bright-cleaning-services',
    providerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    providerPro: true,
    rating: 4.7,
    reviewCount: 145,
    jobsDone: 560,
    location: 'Manchester',
    city: 'Manchester',
    heroImage: 'https://images.unsplash.com/photo-1558618047-f3f7af5780df?w=800',
    gallery: ['https://images.unsplash.com/photo-1558618047-f3f7af5780df?w=800'],
    basePrice: 6000,
    standardPrice: 9500,
    premiumPrice: 14500,
    duration: '2-5 hours',
    responseTime: '< 2 hours',
    nextAvailable: 'Today 3:00 PM',
    featured: false,
    verified: true,
    insured: true,
    urgent: false,
    deliverables: ['Pre-treatment', 'Hot water extraction', 'Stain removal', 'Fast dry'],
    tags: ['Residential', 'Commercial', 'Landlords'],
    lat: 53.4750,
    lng: -2.2500,
  },
]

export const SEED_EMERGENCY_SERVICES: PublicEmergencyService[] = [
  {
    id: '1',
    slug: 'emergency-locksmith-call-out',
    title: 'Emergency Locksmith Call-out',
    subtitle: 'Lockouts, broken locks & urgent entry · 24/7',
    category: 'Locksmith',
    providerName: 'Citywide Locksmiths',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    leadTechnicianName: 'James Wilson',
    leadTechnicianRole: 'Lead Locksmith',
    phone: '0161 123 4567',
    rating: 4.9,
    reviewCount: 238,
    responseTimeMin: 20,
    responseTimeMax: 30,
    heroImage: 'https://images.unsplash.com/photo-1558618047-3c8c76ca6e5b?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'M20'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£5M',
    baseCalloutPrice: 8500,
    noCalloutFee: true,
    description: 'Professional emergency locksmith service covering Greater Manchester 24/7. We specialise in lockouts, lock replacements, key cutting and security upgrades.',
    coverageLat: 53.4808,
    coverageLng: -2.2426,
    priceItems: [
      { service: 'Standard lock open', from: 8500, to: 12000 },
      { service: 'Lock replacement (standard)', from: 12000, to: 18000 },
      { service: 'Anti-snap lock upgrade', from: 18000, to: 28000 },
      { service: 'UPVC door repair', from: 15000, to: 25000 },
      { service: 'Key cutting (per key)', from: 800, to: 1500 },
    ],
  },
  {
    id: '2',
    slug: 'emergency-plumbing-leak',
    title: 'Emergency Plumbing — Leak & Burst Pipe',
    subtitle: 'Immediate response to leaks, floods & burst pipes · 24/7',
    category: 'Plumbing',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    leadTechnicianName: 'Mike Patel',
    leadTechnicianRole: 'Senior Plumber',
    phone: '0161 234 5678',
    rating: 4.8,
    reviewCount: 186,
    responseTimeMin: 25,
    responseTimeMax: 45,
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'M14', 'M15'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£5M',
    baseCalloutPrice: 9500,
    noCalloutFee: false,
    description: 'Emergency plumbing specialists available 24/7 for leaks, burst pipes and flooding. Gas Safe registered for all boiler emergencies.',
    coverageLat: 53.4808,
    coverageLng: -2.2426,
    priceItems: [
      { service: 'Emergency call-out', from: 9500, to: 9500 },
      { service: 'Burst pipe repair', from: 15000, to: 30000 },
      { service: 'Leak detection & repair', from: 12000, to: 25000 },
      { service: 'Stop cock replacement', from: 8000, to: 12000 },
    ],
  },
  {
    id: '3',
    slug: 'emergency-electrician',
    title: 'Emergency Electrician',
    subtitle: 'Power cuts, fuse faults & dangerous wiring · 24/7',
    category: 'Electrical',
    providerName: 'Manchester Electrical Solutions',
    providerSlug: 'manchester-electrical',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    leadTechnicianName: 'Sarah Chen',
    leadTechnicianRole: 'Senior Electrician',
    phone: '0161 345 6789',
    rating: 4.9,
    reviewCount: 142,
    responseTimeMin: 30,
    responseTimeMax: 60,
    heroImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'M16'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£2M',
    baseCalloutPrice: 10000,
    noCalloutFee: false,
    coverageLat: 53.4800,
    coverageLng: -2.2350,
    priceItems: [
      { service: 'Emergency call-out', from: 10000 },
      { service: 'Fuse board investigation', from: 8500 },
      { service: 'Electrical repair', from: 12000, to: 35000 },
    ],
  },
  {
    id: '4',
    slug: 'emergency-boarding-up',
    title: 'Emergency Boarding Up',
    subtitle: 'Broken windows, forced entry & vandalism secured fast',
    category: 'Security',
    providerName: 'Secure It Fast',
    providerSlug: 'premier-property-maintenance',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop',
    leadTechnicianName: 'Tom Hughes',
    leadTechnicianRole: 'Site Manager',
    phone: '0161 456 7890',
    rating: 4.7,
    reviewCount: 89,
    responseTimeMin: 30,
    responseTimeMax: 60,
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£2M',
    baseCalloutPrice: 7500,
    noCalloutFee: true,
    coverageLat: 53.4820,
    coverageLng: -2.2380,
    priceItems: [
      { service: 'Standard window boarding', from: 7500 },
      { service: 'Door boarding', from: 9500 },
      { service: 'Large opening (>2m)', from: 15000 },
    ],
  },
  {
    id: '5',
    slug: 'emergency-gas-engineer',
    title: 'Emergency Gas Engineer',
    subtitle: 'Gas leaks, unsafe appliances & carbon monoxide · 24/7',
    category: 'Gas',
    providerName: 'Citywide Plumbing & Heating',
    providerSlug: 'citywide-plumbing-heating',
    providerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    leadTechnicianName: 'James Wilson',
    leadTechnicianRole: 'Gas Safe Engineer',
    phone: '0161 567 8901',
    rating: 4.9,
    reviewCount: 167,
    responseTimeMin: 20,
    responseTimeMax: 35,
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'M14', 'M15', 'M20'],
    available24h: true,
    policeVetted: true,
    insured: true,
    insuranceAmount: '£5M',
    baseCalloutPrice: 9500,
    noCalloutFee: false,
    coverageLat: 53.4808,
    coverageLng: -2.2426,
    priceItems: [
      { service: 'Emergency call-out', from: 9500 },
      { service: 'Gas leak detection & repair', from: 15000 },
      { service: 'Appliance isolation', from: 8500 },
    ],
  },
  {
    id: '6',
    slug: 'emergency-drain-unblocking',
    title: 'Emergency Drain Unblocking',
    subtitle: 'Blocked drains, toilets & sewers cleared fast · 24/7',
    category: 'Drainage',
    providerName: 'Clear Drains MCR',
    providerSlug: 'northern-waste-management',
    providerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    leadTechnicianName: 'Paul Nash',
    leadTechnicianRole: 'Drainage Specialist',
    phone: '0161 678 9012',
    rating: 4.7,
    reviewCount: 123,
    responseTimeMin: 25,
    responseTimeMax: 50,
    heroImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
    location: 'Greater Manchester',
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6'],
    available24h: true,
    policeVetted: false,
    insured: true,
    insuranceAmount: '£1M',
    baseCalloutPrice: 8000,
    noCalloutFee: true,
    coverageLat: 53.4900,
    coverageLng: -2.2979,
    priceItems: [
      { service: 'Drain unblocking', from: 8000, to: 15000 },
      { service: 'CCTV drain survey', from: 15000 },
      { service: 'High-pressure jetting', from: 12000 },
    ],
  },
]
