-- Performance indexes
CREATE INDEX idx_properties_workspace ON properties(workspace_id);
CREATE INDEX idx_properties_status ON properties(workspace_id, status);
CREATE INDEX idx_property_units_property ON property_units(property_id);
CREATE INDEX idx_tenancies_workspace ON tenancies(workspace_id);
CREATE INDEX idx_tenancies_property ON tenancies(property_id);
CREATE INDEX idx_contacts_workspace ON contacts(workspace_id);
CREATE INDEX idx_contacts_type ON contacts(workspace_id, contact_type);
CREATE INDEX idx_tasks_workspace ON tasks(workspace_id);
CREATE INDEX idx_tasks_status ON tasks(workspace_id, status);
CREATE INDEX idx_tasks_due ON tasks(workspace_id, due_date);
CREATE INDEX idx_jobs_workspace ON jobs(workspace_id);
CREATE INDEX idx_jobs_status ON jobs(workspace_id, status);
CREATE INDEX idx_planning_sets_workspace ON planning_sets(workspace_id);
CREATE INDEX idx_income_workspace ON income_records(workspace_id);
CREATE INDEX idx_income_date ON income_records(workspace_id, date);
CREATE INDEX idx_expense_workspace ON expense_records(workspace_id);
CREATE INDEX idx_invoices_workspace ON invoices(workspace_id);
CREATE INDEX idx_invoices_status ON invoices(workspace_id, status);
CREATE INDEX idx_calendar_workspace ON calendar_events(workspace_id);
CREATE INDEX idx_calendar_start ON calendar_events(workspace_id, start_at);
CREATE INDEX idx_messages_conversation ON messages(conversation_id);
CREATE INDEX idx_ai_messages_thread ON ai_chat_messages(thread_id);
CREATE INDEX idx_audit_workspace ON audit_logs(workspace_id);
CREATE INDEX idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX idx_activity_workspace ON activity_logs(workspace_id);
CREATE INDEX idx_notifications_user ON notifications(user_id, read_at);
CREATE INDEX idx_workspace_members_workspace ON workspace_members(workspace_id);
CREATE INDEX idx_workspace_members_user ON workspace_members(user_id);
