-- Automation node registry — expanded to 85 node types (canvas rebuild).
-- Idempotent upsert: mirrors src/lib/automation/node-registry.ts (build-time truth).

insert into public.automation_node_registry
  (node_type, label, category, scope, risk, min_plan, requires_approval, blocked_from_autorun, enabled, description)
values
  ('record.created','Record Created','trigger','workspace','low','Starter',false,false,true,'Starts when a workspace record is created.'),
  ('record.updated','Record Updated','trigger','workspace','low','Starter',false,false,true,'Starts when any field on a watched record changes.'),
  ('record.deleted','Record Deleted','trigger','workspace','low','Operator',false,false,true,'Starts when a record is archived or deleted.'),
  ('field.changed','Field Changed','trigger','workspace','low','Starter',false,false,true,'Starts when a watched field changes value.'),
  ('portfolio.property_added','Property Added','trigger','portfolio','low','Operator',false,false,true,'Starts when a property is added to the portfolio.'),
  ('portfolio.tenancy_started','Tenancy Started','trigger','portfolio','medium','Operator',false,false,true,'Starts when a new tenancy begins.'),
  ('portfolio.tenancy_ending','Tenancy Ending','trigger','portfolio','medium','Operator',false,false,true,'Starts ahead of a tenancy end date.'),
  ('work.task_created','Task Created','trigger','work','low','Starter',false,false,true,'Starts when a work task is created.'),
  ('work.task_overdue','Task Overdue','trigger','work','medium','Operator',false,false,true,'Starts when a task passes its due date.'),
  ('booking.confirmed','Booking Confirmed','trigger','booking','medium','Pro / Agency',false,false,true,'Starts when a booking becomes confirmed.'),
  ('booking.cancelled','Booking Cancelled','trigger','booking','medium','Pro / Agency',false,false,true,'Starts when a booking is cancelled.'),
  ('booking.checkin_due','Check-in Due','trigger','booking','medium','Pro / Agency',false,false,true,'Starts before a booking check-in.'),
  ('booking.checkout_due','Checkout Due','trigger','booking','medium','Pro / Agency',false,false,true,'Starts before checkout based on local calendar rules.'),
  ('marketplace.transaction.created','Marketplace Transaction Created','trigger','marketplace_transaction','medium','Pro / Agency',false,false,true,'Starts when a marketplace order or transaction is opened.'),
  ('marketplace.order_disputed','Marketplace Order Disputed','trigger','marketplace_transaction','high','Pro / Agency',true,false,true,'Starts when a buyer raises a marketplace dispute.'),
  ('marketplace.review_received','Marketplace Review Received','trigger','marketplace_transaction','low','Pro / Agency',false,false,true,'Starts when a marketplace review is posted.'),
  ('supplier.job.assigned','Supplier Job Assigned','trigger','supplier_job','low','Pro / Agency',false,false,true,'Starts when a supplier is assigned a job.'),
  ('supplier.job.completed','Supplier Job Completed','trigger','supplier_job','medium','Pro / Agency',false,false,true,'Starts when a supplier marks a job complete.'),
  ('supplier.evidence_uploaded','Supplier Evidence Uploaded','trigger','supplier_job','low','Pro / Agency',false,false,true,'Starts when a supplier uploads completion evidence.'),
  ('invoice.overdue','Invoice Overdue','trigger','accounting','medium','Operator',false,false,true,'Starts when an invoice crosses the overdue threshold.'),
  ('money.payment_received','Payment Received','trigger','accounting','low','Operator',false,false,true,'Starts when an inbound payment settles.'),
  ('money.payout_due','Payout Due','trigger','payment','high','Scale',true,false,true,'Starts when a supplier or owner payout becomes due.'),
  ('compliance.expiring','Compliance Expiring','trigger','compliance','high','Operator',true,false,true,'Starts before a certificate, licence, or safety item expires.'),
  ('compliance.failed','Compliance Check Failed','trigger','compliance','high','Operator',true,false,true,'Starts when a compliance check is recorded as failed.'),
  ('legal.review.required','Legal Review Required','trigger','legal','critical','Scale',true,false,true,'Starts review-first legal workflows.'),
  ('ai.signal_detected','AI Signal Detected','trigger','workspace','high','Scale',true,false,true,'Starts when an AI monitor flags a risk or anomaly.'),
  ('schedule.daily','Daily Schedule','trigger','workspace','low','Operator',false,false,true,'Runs once per day at a set local time.'),
  ('schedule.custom_cron','Custom Cron','trigger','workspace','medium','Scale',false,false,true,'Runs on a configured cron schedule with caps.'),
  ('webhook.incoming','Incoming Webhook','webhook','workspace','medium','Scale',false,false,true,'Accepts signed inbound events from an external system.'),
  ('condition.if_else','If / Else','condition','workspace','low','Starter',false,false,true,'Routes records based on a true or false expression.'),
  ('condition.field_compare','Compare Fields','condition','workspace','low','Starter',false,false,true,'Compares two record fields or a field to a constant.'),
  ('condition.entity_state','Entity In State','condition','workspace','low','Operator',false,false,true,'Continues only when an entity is in a given status.'),
  ('condition.plan_allows','If Plan Allows','condition','workspace','low','Starter',false,false,true,'Stops workflows that exceed the workspace plan.'),
  ('condition.within_caps','If Within Safety Caps','condition','workspace','low','Operator',false,false,true,'Continues only when daily safety caps are not exceeded.'),
  ('condition.business_context','Business Context Match','condition','workspace','low','Operator',false,false,true,'Continues based on workspace context (role, region, hours).'),
  ('condition.payment_release_allowed','If Payment Release Allowed','condition','payment','critical','Scale',true,false,true,'Checks disputes, provider state, role gate, and approval state.'),
  ('branch.match_country','Match Country','branch','compliance','medium','Operator',false,false,true,'Routes work by country profile and local rule set.'),
  ('branch.switch','Switch / Router','branch','workspace','low','Operator',false,false,true,'Routes to one of many paths by a key value.'),
  ('branch.split_parallel','Split (Parallel)','branch','workspace','low','Scale',false,false,true,'Fans out to run several paths in parallel.'),
  ('delay.fixed','Wait (Fixed)','delay','workspace','low','Starter',false,false,true,'Waits a fixed amount of time before continuing.'),
  ('delay.until_date','Wait Until Date','delay','workspace','low','Operator',false,false,true,'Waits until a date field is reached.'),
  ('delay.business_hours','Delay For Business Hours','delay','workspace','low','Operator',false,false,true,'Waits until the next allowed local business window.'),
  ('lookup.record','Get Record','lookup','workspace','low','Operator',false,false,true,'Loads a related record by id with RLS.'),
  ('lookup.preferred_suppliers','Get Preferred Suppliers','lookup','supplier_job','medium','Pro / Agency',false,false,true,'Finds workspace-scoped verified suppliers for a job category.'),
  ('lookup.marketplace_transaction','Get Marketplace Transaction','lookup','marketplace_transaction','medium','Pro / Agency',false,false,true,'Loads transaction context with RLS and redaction.'),
  ('lookup.account_balance','Get Account Balance','lookup','accounting','low','Operator',false,false,true,'Reads a ledger account balance (read-only).'),
  ('ai.generate_summary','AI Generate Summary','ai','workspace','medium','Scale',true,false,true,'Summarises context into a draft for review.'),
  ('ai.draft_message','AI Draft Message','ai','customer','medium','Scale',true,false,true,'Creates a draft message for review.'),
  ('ai.classify','AI Classify','ai','workspace','medium','Scale',true,false,true,'Classifies an item into a category for routing.'),
  ('ai.risk_score','AI Risk Score','ai','workspace','high','Scale',true,false,true,'Scores operational risk without taking destructive action.'),
  ('ai.guardrail_check','AI Guardrail Check','ai','workspace','high','Scale',true,false,true,'Runs an AI safety guardrail before a downstream step.'),
  ('action.create_task','Create Task','action','workspace','low','Starter',false,false,true,'Creates a workspace task or reminder.'),
  ('action.update_record','Update Record Field','action','workspace','medium','Operator',false,false,true,'Sets a safe field on the triggering record.'),
  ('action.add_note','Add Note','action','workspace','low','Starter',false,false,true,'Adds a timeline note to a record.'),
  ('action.create_calendar_reminder','Create Calendar Reminder','action','workspace','low','Starter',false,false,true,'Creates a calendar reminder for a date.'),
  ('action.create_cleaning_task','Create Cleaning Task','action','booking','low','Pro / Agency',false,false,true,'Creates a checkout cleaning task for a booking.'),
  ('action.request_supplier_evidence','Request Supplier Evidence','action','supplier_job','medium','Pro / Agency',false,false,true,'Asks a supplier to upload required evidence.'),
  ('action.assign_supplier','Assign Supplier','action','supplier_job','medium','Pro / Agency',false,false,true,'Drafts a supplier assignment for review.'),
  ('action.flag_marketplace_order','Flag Marketplace Order','action','marketplace_transaction','medium','Pro / Agency',false,false,true,'Flags a marketplace order for operator attention.'),
  ('action.create_invoice_draft','Create Invoice Draft','action','accounting','medium','Operator',false,false,true,'Drafts an invoice for review (never auto-issues).'),
  ('action.record_compliance_check','Record Compliance Check','action','compliance','medium','Operator',false,false,true,'Logs a compliance check outcome on a record.'),
  ('legal.create_draft','Create Legal Draft','legal','legal','critical','Scale',true,false,true,'Creates a legal draft without sending or serving it.'),
  ('legal.auto_serve_notice','Auto-Serve Notice','legal','legal','restricted','Enterprise',false,true,true,'Registered as blocked so it cannot be silently automated.'),
  ('comm.internal_notification','Send Internal Notification','communication','workspace','low','Starter',false,false,true,'Sends an in-app notification to a role or owner.'),
  ('comm.external_message_draft','Create External Message Draft','communication','customer','medium','Operator',true,false,true,'Creates a customer, guest, tenant, or supplier message draft.'),
  ('comm.email_draft','Create Email Draft','communication','customer','medium','Operator',true,false,true,'Drafts an email for review (never auto-sends).'),
  ('payment.release_payout_after_approval','Release Payout After Approval','payment','payment','critical','Scale',true,true,true,'Releases payout only after approval and provider checks.'),
  ('payment.issue_refund_after_approval','Issue Refund After Approval','payment','payment','critical','Scale',true,true,true,'Issues a refund only after human approval.'),
  ('payment.capture_after_approval','Capture Payment After Approval','payment','payment','critical','Scale',true,true,true,'Captures a held payment only after approval.'),
  ('approval.request_human','Request Human Approval','approval','workspace','medium','Operator',false,false,true,'Creates an approval item and waits for a decision.'),
  ('approval.request_legal_review','Request Legal Review','approval','legal','critical','Scale',true,false,true,'Routes legal content to a reviewer.'),
  ('approval.request_finance_signoff','Request Finance Sign-off','approval','payment','high','Scale',true,false,true,'Routes a money action to a finance approver.'),
  ('integration.stripe_connect','Stripe Connect','integration','payment','high','Scale',true,false,true,'Uses Stripe Connect under approval, provider, and audit gates.'),
  ('integration.channel_manager_webhook','Channel Manager Webhook','integration','booking','medium','Pro / Agency',false,false,true,'Receives booking channel events through signed webhooks.'),
  ('integration.accounting_sync','Accounting Sync','integration','accounting','medium','Scale',false,false,true,'Pushes a draft entry to a connected accounting system.'),
  ('webhook.outgoing','Outgoing Webhook','webhook','workspace','medium','Scale',false,false,true,'Posts a signed event to a configured endpoint.'),
  ('utility.redact_sensitive_data','Redact Sensitive Data','utility','workspace','low','Starter',false,false,true,'Removes sensitive fields before logs or external calls.'),
  ('utility.set_variable','Set Variable','utility','workspace','low','Starter',false,false,true,'Stores a computed value for later nodes.'),
  ('utility.format_text','Format Text','utility','workspace','low','Starter',false,false,true,'Builds a string from tokens and record facts.'),
  ('error.retry_with_backoff','Retry With Backoff','error','workspace','low','Operator',false,false,true,'Retries failed nodes before stopping or falling back.'),
  ('error.pause_after_threshold','Pause After Threshold','error','workspace','medium','Operator',false,false,true,'Pauses repeated failures and notifies the owner.'),
  ('error.fallback_path','Fallback Path','error','workspace','low','Operator',false,false,true,'Routes to a safe fallback branch on failure.'),
  ('end.success','End Success','end','workspace','low','Starter',false,false,true,'Marks the run complete.'),
  ('end.waiting_approval','End Waiting Approval','end','workspace','low','Starter',false,false,true,'Ends a run while an approval is pending.'),
  ('end.stopped','End Stopped','end','workspace','low','Operator',false,false,true,'Ends a run early on a condition mismatch.')
on conflict (node_type) do update set
  label = excluded.label, category = excluded.category, scope = excluded.scope,
  risk = excluded.risk, min_plan = excluded.min_plan, requires_approval = excluded.requires_approval,
  blocked_from_autorun = excluded.blocked_from_autorun, description = excluded.description, updated_at = now();
