"use client"

import {
  Building2,
  Users,
  ShieldCheck,
  Scale,
  CreditCard,
  Package,
  Receipt,
  Sparkles,
  MessageCircle,
  Bell,
  Palette,
  Globe,
  Navigation,
  Plug,
  Workflow,
  Mail,
  HardDrive,
  Lock,
  Key,
  ClipboardList,
  Database,
  FlaskConical,
  AlertTriangle,
  Settings2,
} from "lucide-react"
import type { SettingsNavItem } from "./SettingsShell"

export const WORKSPACE_NAV: SettingsNavItem[] = [
  {
    key: "overview",
    label: "Overview",
    href: "/property-manager/workspace-settings",
    icon: Building2,
  },
  // General
  {
    key: "profile",
    label: "Workspace Profile",
    href: "/property-manager/workspace-settings/profile",
    icon: Building2,
    group: "General",
  },
  {
    key: "team",
    label: "Team",
    href: "/property-manager/workspace-settings/team",
    icon: Users,
    group: "General",
  },
  {
    key: "roles",
    label: "Roles & Permissions",
    href: "/property-manager/workspace-settings/roles",
    icon: ShieldCheck,
    group: "General",
  },
  // Billing
  {
    key: "subscription",
    label: "Subscription",
    href: "/property-manager/workspace-settings/subscription",
    icon: CreditCard,
    group: "Billing",
  },
  {
    key: "addons",
    label: "Add-ons",
    href: "/property-manager/workspace-settings/addons",
    icon: Package,
    group: "Billing",
  },
  {
    key: "billing",
    label: "Billing & Payment",
    href: "/property-manager/workspace-settings/billing",
    icon: Receipt,
    group: "Billing",
  },
  {
    key: "invoices",
    label: "Invoices",
    href: "/property-manager/workspace-settings/invoices",
    icon: Receipt,
    group: "Billing",
  },
  // AI
  {
    key: "ai",
    label: "AI Credits",
    href: "/property-manager/workspace-settings/ai",
    icon: Sparkles,
    group: "AI",
  },
  {
    key: "copilot-inbox",
    label: "Copilot & Inbox",
    href: "/property-manager/workspace-settings/copilot-inbox",
    icon: MessageCircle,
    group: "AI",
  },
  // Configuration
  {
    key: "notifications",
    label: "Notifications",
    href: "/property-manager/workspace-settings/notifications",
    icon: Bell,
    group: "Configuration",
  },
  {
    key: "branding",
    label: "Branding",
    href: "/property-manager/workspace-settings/branding",
    icon: Palette,
    group: "Configuration",
  },
  {
    key: "white-label",
    label: "White Label",
    href: "/property-manager/workspace-settings/white-label",
    icon: Globe,
    group: "Configuration",
    locked: false,
  },
  {
    key: "preferences",
    label: "Preferences",
    href: "/property-manager/workspace-settings/preferences",
    icon: Settings2,
    group: "Configuration",
  },
  {
    key: "jurisdiction",
    label: "Jurisdiction",
    href: "/property-manager/workspace-settings/jurisdiction",
    icon: Scale,
    group: "Configuration",
  },
  {
    key: "navigation",
    label: "Menu Builder",
    href: "/property-manager/workspace-settings/navigation",
    icon: Navigation,
    group: "Configuration",
  },
  {
    key: "integrations",
    label: "Integrations",
    href: "/property-manager/workspace-settings/integrations",
    icon: Plug,
    group: "Configuration",
  },
  {
    key: "automations",
    label: "Automation Governance",
    href: "/property-manager/workspace-settings/automations",
    icon: Workflow,
    group: "Configuration",
  },
  {
    key: "email",
    label: "Email & SMTP",
    href: "/property-manager/workspace-settings/email",
    icon: Mail,
    group: "Configuration",
  },
  {
    key: "storage",
    label: "Storage",
    href: "/property-manager/workspace-settings/storage",
    icon: HardDrive,
    group: "Configuration",
  },
  // Security
  {
    key: "security",
    label: "Security",
    href: "/property-manager/workspace-settings/security",
    icon: Lock,
    group: "Security",
  },
  {
    key: "sso",
    label: "SAML / SSO",
    href: "/property-manager/workspace-settings/sso",
    icon: Key,
    group: "Security",
  },
  {
    key: "audit",
    label: "Audit Logs",
    href: "/property-manager/workspace-settings/audit",
    icon: ClipboardList,
    group: "Security",
  },
  // Advanced
  {
    key: "data",
    label: "Data & Exports",
    href: "/property-manager/workspace-settings/data",
    icon: Database,
    group: "Advanced",
  },
  {
    key: "demo-data",
    label: "Demo Data",
    href: "/property-manager/workspace-settings/demo-data",
    icon: FlaskConical,
    group: "Advanced",
  },
  {
    key: "danger-zone",
    label: "Danger Zone",
    href: "/property-manager/workspace-settings/danger-zone",
    icon: AlertTriangle,
    group: "Advanced",
  },
]
